/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainAnalyticsPublisherResponse } from './DomainAnalyticsPublisherResponse';
import {
    DomainAnalyticsPublisherResponseFromJSON,
    DomainAnalyticsPublisherResponseFromJSONTyped,
    DomainAnalyticsPublisherResponseToJSON,
    DomainAnalyticsPublisherResponseToJSONTyped,
} from './DomainAnalyticsPublisherResponse';

/**
 * 
 * @export
 * @interface AnalyticsAffiliatesIdGet200Response
 */
export interface AnalyticsAffiliatesIdGet200Response {
    /**
     * 
     * @type {DomainAnalyticsPublisherResponse}
     * @memberof AnalyticsAffiliatesIdGet200Response
     */
    data?: DomainAnalyticsPublisherResponse;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsAffiliatesIdGet200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the AnalyticsAffiliatesIdGet200Response interface.
 */
export function instanceOfAnalyticsAffiliatesIdGet200Response(value: object): value is AnalyticsAffiliatesIdGet200Response {
    return true;
}

export function AnalyticsAffiliatesIdGet200ResponseFromJSON(json: any): AnalyticsAffiliatesIdGet200Response {
    return AnalyticsAffiliatesIdGet200ResponseFromJSONTyped(json, false);
}

export function AnalyticsAffiliatesIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsAffiliatesIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DomainAnalyticsPublisherResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AnalyticsAffiliatesIdGet200ResponseToJSON(json: any): AnalyticsAffiliatesIdGet200Response {
    return AnalyticsAffiliatesIdGet200ResponseToJSONTyped(json, false);
}

export function AnalyticsAffiliatesIdGet200ResponseToJSONTyped(value?: AnalyticsAffiliatesIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DomainAnalyticsPublisherResponseToJSON(value['data']),
        'message': value['message'],
    };
}

