/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainAnalyticsAdvertiser } from './DomainAnalyticsAdvertiser';
import {
    DomainAnalyticsAdvertiserFromJSON,
    DomainAnalyticsAdvertiserFromJSONTyped,
    DomainAnalyticsAdvertiserToJSON,
    DomainAnalyticsAdvertiserToJSONTyped,
} from './DomainAnalyticsAdvertiser';

/**
 * 
 * @export
 * @interface AnalyticsAdvertisersPost201Response
 */
export interface AnalyticsAdvertisersPost201Response {
    /**
     * 
     * @type {DomainAnalyticsAdvertiser}
     * @memberof AnalyticsAdvertisersPost201Response
     */
    data?: DomainAnalyticsAdvertiser;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsAdvertisersPost201Response
     */
    message?: string;
}

/**
 * Check if a given object implements the AnalyticsAdvertisersPost201Response interface.
 */
export function instanceOfAnalyticsAdvertisersPost201Response(value: object): value is AnalyticsAdvertisersPost201Response {
    return true;
}

export function AnalyticsAdvertisersPost201ResponseFromJSON(json: any): AnalyticsAdvertisersPost201Response {
    return AnalyticsAdvertisersPost201ResponseFromJSONTyped(json, false);
}

export function AnalyticsAdvertisersPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsAdvertisersPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DomainAnalyticsAdvertiserFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AnalyticsAdvertisersPost201ResponseToJSON(json: any): AnalyticsAdvertisersPost201Response {
    return AnalyticsAdvertisersPost201ResponseToJSONTyped(json, false);
}

export function AnalyticsAdvertisersPost201ResponseToJSONTyped(value?: AnalyticsAdvertisersPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DomainAnalyticsAdvertiserToJSON(value['data']),
        'message': value['message'],
    };
}

