/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainAnalyticsPublisher } from './DomainAnalyticsPublisher';
import {
    DomainAnalyticsPublisherFromJSON,
    DomainAnalyticsPublisherFromJSONTyped,
    DomainAnalyticsPublisherToJSON,
    DomainAnalyticsPublisherToJSONTyped,
} from './DomainAnalyticsPublisher';

/**
 * 
 * @export
 * @interface ApiV1AnalyticsAffiliatesPost201Response
 */
export interface ApiV1AnalyticsAffiliatesPost201Response {
    /**
     * 
     * @type {DomainAnalyticsPublisher}
     * @memberof ApiV1AnalyticsAffiliatesPost201Response
     */
    data?: DomainAnalyticsPublisher;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AnalyticsAffiliatesPost201Response
     */
    message?: string;
}

/**
 * Check if a given object implements the ApiV1AnalyticsAffiliatesPost201Response interface.
 */
export function instanceOfApiV1AnalyticsAffiliatesPost201Response(value: object): value is ApiV1AnalyticsAffiliatesPost201Response {
    return true;
}

export function ApiV1AnalyticsAffiliatesPost201ResponseFromJSON(json: any): ApiV1AnalyticsAffiliatesPost201Response {
    return ApiV1AnalyticsAffiliatesPost201ResponseFromJSONTyped(json, false);
}

export function ApiV1AnalyticsAffiliatesPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1AnalyticsAffiliatesPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DomainAnalyticsPublisherFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ApiV1AnalyticsAffiliatesPost201ResponseToJSON(json: any): ApiV1AnalyticsAffiliatesPost201Response {
    return ApiV1AnalyticsAffiliatesPost201ResponseToJSONTyped(json, false);
}

export function ApiV1AnalyticsAffiliatesPost201ResponseToJSONTyped(value?: ApiV1AnalyticsAffiliatesPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DomainAnalyticsPublisherToJSON(value['data']),
        'message': value['message'],
    };
}

