/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainAutocompleteResult } from './DomainAutocompleteResult';
import {
    DomainAutocompleteResultFromJSON,
    DomainAutocompleteResultFromJSONTyped,
    DomainAutocompleteResultToJSON,
    DomainAutocompleteResultToJSONTyped,
} from './DomainAutocompleteResult';

/**
 * 
 * @export
 * @interface ApiV1AnalyticsAutocompleteGet200Response
 */
export interface ApiV1AnalyticsAutocompleteGet200Response {
    /**
     * 
     * @type {Array<DomainAutocompleteResult>}
     * @memberof ApiV1AnalyticsAutocompleteGet200Response
     */
    data?: Array<DomainAutocompleteResult>;
    /**
     * 
     * @type {string}
     * @memberof ApiV1AnalyticsAutocompleteGet200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the ApiV1AnalyticsAutocompleteGet200Response interface.
 */
export function instanceOfApiV1AnalyticsAutocompleteGet200Response(value: object): value is ApiV1AnalyticsAutocompleteGet200Response {
    return true;
}

export function ApiV1AnalyticsAutocompleteGet200ResponseFromJSON(json: any): ApiV1AnalyticsAutocompleteGet200Response {
    return ApiV1AnalyticsAutocompleteGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1AnalyticsAutocompleteGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1AnalyticsAutocompleteGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DomainAutocompleteResultFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ApiV1AnalyticsAutocompleteGet200ResponseToJSON(json: any): ApiV1AnalyticsAutocompleteGet200Response {
    return ApiV1AnalyticsAutocompleteGet200ResponseToJSONTyped(json, false);
}

export function ApiV1AnalyticsAutocompleteGet200ResponseToJSONTyped(value?: ApiV1AnalyticsAutocompleteGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DomainAutocompleteResultToJSON)),
        'message': value['message'],
    };
}

