/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainAdvertiser
 */
export interface DomainAdvertiser {
    /**
     * 
     * @type {number}
     * @memberof DomainAdvertiser
     */
    advertiserId?: number;
    /**
     * JSONB stored as string
     * @type {string}
     * @memberof DomainAdvertiser
     */
    billingDetails?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAdvertiser
     */
    contactEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAdvertiser
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAdvertiser
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainAdvertiser
     */
    organizationId?: number;
    /**
     * 'active', 'pending', 'inactive', 'rejected'
     * @type {string}
     * @memberof DomainAdvertiser
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAdvertiser
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the DomainAdvertiser interface.
 */
export function instanceOfDomainAdvertiser(value: object): value is DomainAdvertiser {
    return true;
}

export function DomainAdvertiserFromJSON(json: any): DomainAdvertiser {
    return DomainAdvertiserFromJSONTyped(json, false);
}

export function DomainAdvertiserFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainAdvertiser {
    if (json == null) {
        return json;
    }
    return {
        
        'advertiserId': json['advertiser_id'] == null ? undefined : json['advertiser_id'],
        'billingDetails': json['billing_details'] == null ? undefined : json['billing_details'],
        'contactEmail': json['contact_email'] == null ? undefined : json['contact_email'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'name': json['name'] == null ? undefined : json['name'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function DomainAdvertiserToJSON(json: any): DomainAdvertiser {
    return DomainAdvertiserToJSONTyped(json, false);
}

export function DomainAdvertiserToJSONTyped(value?: DomainAdvertiser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advertiser_id': value['advertiserId'],
        'billing_details': value['billingDetails'],
        'contact_email': value['contactEmail'],
        'created_at': value['createdAt'],
        'name': value['name'],
        'organization_id': value['organizationId'],
        'status': value['status'],
        'updated_at': value['updatedAt'],
    };
}

