/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainPerformanceTimeSeriesPoint
 */
export interface DomainPerformanceTimeSeriesPoint {
    /**
     * 
     * @type {number}
     * @memberof DomainPerformanceTimeSeriesPoint
     */
    clickThroughRate?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainPerformanceTimeSeriesPoint
     */
    clicks?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainPerformanceTimeSeriesPoint
     */
    conversionRate?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainPerformanceTimeSeriesPoint
     */
    conversions?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainPerformanceTimeSeriesPoint
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainPerformanceTimeSeriesPoint
     */
    impressions?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainPerformanceTimeSeriesPoint
     */
    revenue?: number;
}

/**
 * Check if a given object implements the DomainPerformanceTimeSeriesPoint interface.
 */
export function instanceOfDomainPerformanceTimeSeriesPoint(value: object): value is DomainPerformanceTimeSeriesPoint {
    return true;
}

export function DomainPerformanceTimeSeriesPointFromJSON(json: any): DomainPerformanceTimeSeriesPoint {
    return DomainPerformanceTimeSeriesPointFromJSONTyped(json, false);
}

export function DomainPerformanceTimeSeriesPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainPerformanceTimeSeriesPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'clickThroughRate': json['click_through_rate'] == null ? undefined : json['click_through_rate'],
        'clicks': json['clicks'] == null ? undefined : json['clicks'],
        'conversionRate': json['conversion_rate'] == null ? undefined : json['conversion_rate'],
        'conversions': json['conversions'] == null ? undefined : json['conversions'],
        'date': json['date'] == null ? undefined : json['date'],
        'impressions': json['impressions'] == null ? undefined : json['impressions'],
        'revenue': json['revenue'] == null ? undefined : json['revenue'],
    };
}

export function DomainPerformanceTimeSeriesPointToJSON(json: any): DomainPerformanceTimeSeriesPoint {
    return DomainPerformanceTimeSeriesPointToJSONTyped(json, false);
}

export function DomainPerformanceTimeSeriesPointToJSONTyped(value?: DomainPerformanceTimeSeriesPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'click_through_rate': value['clickThroughRate'],
        'clicks': value['clicks'],
        'conversion_rate': value['conversionRate'],
        'conversions': value['conversions'],
        'date': value['date'],
        'impressions': value['impressions'],
        'revenue': value['revenue'],
    };
}

