/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DomainDelegationStatus = {
    DelegationStatusPending: 'pending',
    DelegationStatusActive: 'active',
    DelegationStatusSuspended: 'suspended',
    DelegationStatusRevoked: 'revoked'
} as const;
export type DomainDelegationStatus = typeof DomainDelegationStatus[keyof typeof DomainDelegationStatus];


export function instanceOfDomainDelegationStatus(value: any): boolean {
    for (const key in DomainDelegationStatus) {
        if (Object.prototype.hasOwnProperty.call(DomainDelegationStatus, key)) {
            if (DomainDelegationStatus[key as keyof typeof DomainDelegationStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DomainDelegationStatusFromJSON(json: any): DomainDelegationStatus {
    return DomainDelegationStatusFromJSONTyped(json, false);
}

export function DomainDelegationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainDelegationStatus {
    return json as DomainDelegationStatus;
}

export function DomainDelegationStatusToJSON(value?: DomainDelegationStatus | null): any {
    return value as any;
}

export function DomainDelegationStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): DomainDelegationStatus {
    return value as DomainDelegationStatus;
}

