/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainDailyPerformanceReport
 */
export interface DomainDailyPerformanceReport {
    /**
     * 
     * @type {string}
     * @memberof DomainDailyPerformanceReport
     */
    campaignId?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainDailyPerformanceReport
     */
    campaignName?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainDailyPerformanceReport
     */
    clickThroughRate?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainDailyPerformanceReport
     */
    clicks?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainDailyPerformanceReport
     */
    conversionRate?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainDailyPerformanceReport
     */
    conversions?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainDailyPerformanceReport
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainDailyPerformanceReport
     */
    impressions?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainDailyPerformanceReport
     */
    payouts?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainDailyPerformanceReport
     */
    revenue?: number;
}

/**
 * Check if a given object implements the DomainDailyPerformanceReport interface.
 */
export function instanceOfDomainDailyPerformanceReport(value: object): value is DomainDailyPerformanceReport {
    return true;
}

export function DomainDailyPerformanceReportFromJSON(json: any): DomainDailyPerformanceReport {
    return DomainDailyPerformanceReportFromJSONTyped(json, false);
}

export function DomainDailyPerformanceReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainDailyPerformanceReport {
    if (json == null) {
        return json;
    }
    return {
        
        'campaignId': json['campaign_id'] == null ? undefined : json['campaign_id'],
        'campaignName': json['campaign_name'] == null ? undefined : json['campaign_name'],
        'clickThroughRate': json['click_through_rate'] == null ? undefined : json['click_through_rate'],
        'clicks': json['clicks'] == null ? undefined : json['clicks'],
        'conversionRate': json['conversion_rate'] == null ? undefined : json['conversion_rate'],
        'conversions': json['conversions'] == null ? undefined : json['conversions'],
        'date': json['date'] == null ? undefined : json['date'],
        'impressions': json['impressions'] == null ? undefined : json['impressions'],
        'payouts': json['payouts'] == null ? undefined : json['payouts'],
        'revenue': json['revenue'] == null ? undefined : json['revenue'],
    };
}

export function DomainDailyPerformanceReportToJSON(json: any): DomainDailyPerformanceReport {
    return DomainDailyPerformanceReportToJSONTyped(json, false);
}

export function DomainDailyPerformanceReportToJSONTyped(value?: DomainDailyPerformanceReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'campaign_id': value['campaignId'],
        'campaign_name': value['campaignName'],
        'click_through_rate': value['clickThroughRate'],
        'clicks': value['clicks'],
        'conversion_rate': value['conversionRate'],
        'conversions': value['conversions'],
        'date': value['date'],
        'impressions': value['impressions'],
        'payouts': value['payouts'],
        'revenue': value['revenue'],
    };
}

