/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DomainBillingAccountStatus = {
    BillingAccountStatusActive: 'active',
    BillingAccountStatusSuspended: 'suspended',
    BillingAccountStatusClosed: 'closed'
} as const;
export type DomainBillingAccountStatus = typeof DomainBillingAccountStatus[keyof typeof DomainBillingAccountStatus];


export function instanceOfDomainBillingAccountStatus(value: any): boolean {
    for (const key in DomainBillingAccountStatus) {
        if (Object.prototype.hasOwnProperty.call(DomainBillingAccountStatus, key)) {
            if (DomainBillingAccountStatus[key as keyof typeof DomainBillingAccountStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DomainBillingAccountStatusFromJSON(json: any): DomainBillingAccountStatus {
    return DomainBillingAccountStatusFromJSONTyped(json, false);
}

export function DomainBillingAccountStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainBillingAccountStatus {
    return json as DomainBillingAccountStatus;
}

export function DomainBillingAccountStatusToJSON(value?: DomainBillingAccountStatus | null): any {
    return value as any;
}

export function DomainBillingAccountStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): DomainBillingAccountStatus {
    return value as DomainBillingAccountStatus;
}

