/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DomainPaymentMethodStatus = {
    PaymentMethodStatusActive: 'active',
    PaymentMethodStatusInactive: 'inactive',
    PaymentMethodStatusExpired: 'expired',
    PaymentMethodStatusFailed: 'failed'
} as const;
export type DomainPaymentMethodStatus = typeof DomainPaymentMethodStatus[keyof typeof DomainPaymentMethodStatus];


export function instanceOfDomainPaymentMethodStatus(value: any): boolean {
    for (const key in DomainPaymentMethodStatus) {
        if (Object.prototype.hasOwnProperty.call(DomainPaymentMethodStatus, key)) {
            if (DomainPaymentMethodStatus[key as keyof typeof DomainPaymentMethodStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DomainPaymentMethodStatusFromJSON(json: any): DomainPaymentMethodStatus {
    return DomainPaymentMethodStatusFromJSONTyped(json, false);
}

export function DomainPaymentMethodStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainPaymentMethodStatus {
    return json as DomainPaymentMethodStatus;
}

export function DomainPaymentMethodStatusToJSON(value?: DomainPaymentMethodStatus | null): any {
    return value as any;
}

export function DomainPaymentMethodStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): DomainPaymentMethodStatus {
    return value as DomainPaymentMethodStatus;
}

