/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DomainInvitationStatus = {
    InvitationStatusActive: 'active',
    InvitationStatusDisabled: 'disabled',
    InvitationStatusExpired: 'expired'
} as const;
export type DomainInvitationStatus = typeof DomainInvitationStatus[keyof typeof DomainInvitationStatus];


export function instanceOfDomainInvitationStatus(value: any): boolean {
    for (const key in DomainInvitationStatus) {
        if (Object.prototype.hasOwnProperty.call(DomainInvitationStatus, key)) {
            if (DomainInvitationStatus[key as keyof typeof DomainInvitationStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DomainInvitationStatusFromJSON(json: any): DomainInvitationStatus {
    return DomainInvitationStatusFromJSONTyped(json, false);
}

export function DomainInvitationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainInvitationStatus {
    return json as DomainInvitationStatus;
}

export function DomainInvitationStatusToJSON(value?: DomainInvitationStatus | null): any {
    return value as any;
}

export function DomainInvitationStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): DomainInvitationStatus {
    return value as DomainInvitationStatus;
}

