/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainAnalyticsPublisher
 */
export interface DomainAnalyticsPublisher {
    /**
     * 
     * @type {string}
     * @memberof DomainAnalyticsPublisher
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAnalyticsPublisher
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAnalyticsPublisher
     */
    domain?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAnalyticsPublisher
     */
    faviconImageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainAnalyticsPublisher
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DomainAnalyticsPublisher
     */
    known?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DomainAnalyticsPublisher
     */
    promotype?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainAnalyticsPublisher
     */
    relevance?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainAnalyticsPublisher
     */
    screenshotImageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainAnalyticsPublisher
     */
    trafficScore?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainAnalyticsPublisher
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the DomainAnalyticsPublisher interface.
 */
export function instanceOfDomainAnalyticsPublisher(value: object): value is DomainAnalyticsPublisher {
    return true;
}

export function DomainAnalyticsPublisherFromJSON(json: any): DomainAnalyticsPublisher {
    return DomainAnalyticsPublisherFromJSONTyped(json, false);
}

export function DomainAnalyticsPublisherFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainAnalyticsPublisher {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'description': json['description'] == null ? undefined : json['description'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'faviconImageUrl': json['favicon_image_url'] == null ? undefined : json['favicon_image_url'],
        'id': json['id'] == null ? undefined : json['id'],
        'known': json['known'] == null ? undefined : json['known'],
        'promotype': json['promotype'] == null ? undefined : json['promotype'],
        'relevance': json['relevance'] == null ? undefined : json['relevance'],
        'screenshotImageUrl': json['screenshot_image_url'] == null ? undefined : json['screenshot_image_url'],
        'trafficScore': json['traffic_score'] == null ? undefined : json['traffic_score'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function DomainAnalyticsPublisherToJSON(json: any): DomainAnalyticsPublisher {
    return DomainAnalyticsPublisherToJSONTyped(json, false);
}

export function DomainAnalyticsPublisherToJSONTyped(value?: DomainAnalyticsPublisher | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'description': value['description'],
        'domain': value['domain'],
        'favicon_image_url': value['faviconImageUrl'],
        'id': value['id'],
        'known': value['known'],
        'promotype': value['promotype'],
        'relevance': value['relevance'],
        'screenshot_image_url': value['screenshotImageUrl'],
        'traffic_score': value['trafficScore'],
        'updated_at': value['updatedAt'],
    };
}

