/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainVerticalData } from './DomainVerticalData';
import {
    DomainVerticalDataFromJSON,
    DomainVerticalDataFromJSONTyped,
    DomainVerticalDataToJSON,
    DomainVerticalDataToJSONTyped,
} from './DomainVerticalData';
import type { DomainMetaData } from './DomainMetaData';
import {
    DomainMetaDataFromJSON,
    DomainMetaDataFromJSONTyped,
    DomainMetaDataToJSON,
    DomainMetaDataToJSONTyped,
} from './DomainMetaData';
import type { DomainAffiliateNetworkData } from './DomainAffiliateNetworkData';
import {
    DomainAffiliateNetworkDataFromJSON,
    DomainAffiliateNetworkDataFromJSONTyped,
    DomainAffiliateNetworkDataToJSON,
    DomainAffiliateNetworkDataToJSONTyped,
} from './DomainAffiliateNetworkData';
import type { DomainContactEmailData } from './DomainContactEmailData';
import {
    DomainContactEmailDataFromJSON,
    DomainContactEmailDataFromJSONTyped,
    DomainContactEmailDataToJSON,
    DomainContactEmailDataToJSONTyped,
} from './DomainContactEmailData';
import type { DomainSocialMediaData } from './DomainSocialMediaData';
import {
    DomainSocialMediaDataFromJSON,
    DomainSocialMediaDataFromJSONTyped,
    DomainSocialMediaDataToJSON,
    DomainSocialMediaDataToJSONTyped,
} from './DomainSocialMediaData';
import type { DomainKeywordData } from './DomainKeywordData';
import {
    DomainKeywordDataFromJSON,
    DomainKeywordDataFromJSONTyped,
    DomainKeywordDataToJSON,
    DomainKeywordDataToJSONTyped,
} from './DomainKeywordData';

/**
 * 
 * @export
 * @interface DomainAnalyticsAdvertiserResponseAdvertiser
 */
export interface DomainAnalyticsAdvertiserResponseAdvertiser {
    /**
     * 
     * @type {DomainAffiliateNetworkData}
     * @memberof DomainAnalyticsAdvertiserResponseAdvertiser
     */
    affiliateNetworks?: DomainAffiliateNetworkData;
    /**
     * 
     * @type {object}
     * @memberof DomainAnalyticsAdvertiserResponseAdvertiser
     */
    backlinks?: object;
    /**
     * 
     * @type {DomainContactEmailData}
     * @memberof DomainAnalyticsAdvertiserResponseAdvertiser
     */
    contactEmails?: DomainContactEmailData;
    /**
     * 
     * @type {string}
     * @memberof DomainAnalyticsAdvertiserResponseAdvertiser
     */
    domain?: string;
    /**
     * 
     * @type {DomainKeywordData}
     * @memberof DomainAnalyticsAdvertiserResponseAdvertiser
     */
    keywords?: DomainKeywordData;
    /**
     * 
     * @type {DomainMetaData}
     * @memberof DomainAnalyticsAdvertiserResponseAdvertiser
     */
    metaData?: DomainMetaData;
    /**
     * 
     * @type {object}
     * @memberof DomainAnalyticsAdvertiserResponseAdvertiser
     */
    partnerInformation?: object;
    /**
     * 
     * @type {object}
     * @memberof DomainAnalyticsAdvertiserResponseAdvertiser
     */
    relatedAdvertisers?: object;
    /**
     * 
     * @type {DomainSocialMediaData}
     * @memberof DomainAnalyticsAdvertiserResponseAdvertiser
     */
    socialMedia?: DomainSocialMediaData;
    /**
     * 
     * @type {DomainVerticalData}
     * @memberof DomainAnalyticsAdvertiserResponseAdvertiser
     */
    verticals?: DomainVerticalData;
}

/**
 * Check if a given object implements the DomainAnalyticsAdvertiserResponseAdvertiser interface.
 */
export function instanceOfDomainAnalyticsAdvertiserResponseAdvertiser(value: object): value is DomainAnalyticsAdvertiserResponseAdvertiser {
    return true;
}

export function DomainAnalyticsAdvertiserResponseAdvertiserFromJSON(json: any): DomainAnalyticsAdvertiserResponseAdvertiser {
    return DomainAnalyticsAdvertiserResponseAdvertiserFromJSONTyped(json, false);
}

export function DomainAnalyticsAdvertiserResponseAdvertiserFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainAnalyticsAdvertiserResponseAdvertiser {
    if (json == null) {
        return json;
    }
    return {
        
        'affiliateNetworks': json['affiliateNetworks'] == null ? undefined : DomainAffiliateNetworkDataFromJSON(json['affiliateNetworks']),
        'backlinks': json['backlinks'] == null ? undefined : json['backlinks'],
        'contactEmails': json['contactEmails'] == null ? undefined : DomainContactEmailDataFromJSON(json['contactEmails']),
        'domain': json['domain'] == null ? undefined : json['domain'],
        'keywords': json['keywords'] == null ? undefined : DomainKeywordDataFromJSON(json['keywords']),
        'metaData': json['metaData'] == null ? undefined : DomainMetaDataFromJSON(json['metaData']),
        'partnerInformation': json['partnerInformation'] == null ? undefined : json['partnerInformation'],
        'relatedAdvertisers': json['relatedAdvertisers'] == null ? undefined : json['relatedAdvertisers'],
        'socialMedia': json['socialMedia'] == null ? undefined : DomainSocialMediaDataFromJSON(json['socialMedia']),
        'verticals': json['verticals'] == null ? undefined : DomainVerticalDataFromJSON(json['verticals']),
    };
}

export function DomainAnalyticsAdvertiserResponseAdvertiserToJSON(json: any): DomainAnalyticsAdvertiserResponseAdvertiser {
    return DomainAnalyticsAdvertiserResponseAdvertiserToJSONTyped(json, false);
}

export function DomainAnalyticsAdvertiserResponseAdvertiserToJSONTyped(value?: DomainAnalyticsAdvertiserResponseAdvertiser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'affiliateNetworks': DomainAffiliateNetworkDataToJSON(value['affiliateNetworks']),
        'backlinks': value['backlinks'],
        'contactEmails': DomainContactEmailDataToJSON(value['contactEmails']),
        'domain': value['domain'],
        'keywords': DomainKeywordDataToJSON(value['keywords']),
        'metaData': DomainMetaDataToJSON(value['metaData']),
        'partnerInformation': value['partnerInformation'],
        'relatedAdvertisers': value['relatedAdvertisers'],
        'socialMedia': DomainSocialMediaDataToJSON(value['socialMedia']),
        'verticals': DomainVerticalDataToJSON(value['verticals']),
    };
}

