/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainActivity } from './DomainActivity';
import {
    DomainActivityFromJSON,
    DomainActivityFromJSONTyped,
    DomainActivityToJSON,
    DomainActivityToJSONTyped,
} from './DomainActivity';

/**
 * 
 * @export
 * @interface DomainActivityResponse
 */
export interface DomainActivityResponse {
    /**
     * 
     * @type {Array<DomainActivity>}
     * @memberof DomainActivityResponse
     */
    activities?: Array<DomainActivity>;
    /**
     * 
     * @type {boolean}
     * @memberof DomainActivityResponse
     */
    hasMore?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DomainActivityResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the DomainActivityResponse interface.
 */
export function instanceOfDomainActivityResponse(value: object): value is DomainActivityResponse {
    return true;
}

export function DomainActivityResponseFromJSON(json: any): DomainActivityResponse {
    return DomainActivityResponseFromJSONTyped(json, false);
}

export function DomainActivityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainActivityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'activities': json['activities'] == null ? undefined : ((json['activities'] as Array<any>).map(DomainActivityFromJSON)),
        'hasMore': json['has_more'] == null ? undefined : json['has_more'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function DomainActivityResponseToJSON(json: any): DomainActivityResponse {
    return DomainActivityResponseToJSONTyped(json, false);
}

export function DomainActivityResponseToJSONTyped(value?: DomainActivityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activities': value['activities'] == null ? undefined : ((value['activities'] as Array<any>).map(DomainActivityToJSON)),
        'has_more': value['hasMore'],
        'total': value['total'],
    };
}

