/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DomainBillingFrequency = {
    BillingFrequencyWeekly: 'weekly',
    BillingFrequencyBimonthly: 'bimonthly',
    BillingFrequencyMonthly: 'monthly',
    BillingFrequencyTwoMonths: 'two_months',
    BillingFrequencyQuarterly: 'quarterly',
    BillingFrequencyManual: 'manual',
    BillingFrequencyOther: 'other'
} as const;
export type DomainBillingFrequency = typeof DomainBillingFrequency[keyof typeof DomainBillingFrequency];


export function instanceOfDomainBillingFrequency(value: any): boolean {
    for (const key in DomainBillingFrequency) {
        if (Object.prototype.hasOwnProperty.call(DomainBillingFrequency, key)) {
            if (DomainBillingFrequency[key as keyof typeof DomainBillingFrequency] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DomainBillingFrequencyFromJSON(json: any): DomainBillingFrequency {
    return DomainBillingFrequencyFromJSONTyped(json, false);
}

export function DomainBillingFrequencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainBillingFrequency {
    return json as DomainBillingFrequency;
}

export function DomainBillingFrequencyToJSON(value?: DomainBillingFrequency | null): any {
    return value as any;
}

export function DomainBillingFrequencyToJSONTyped(value: any, ignoreDiscriminator: boolean): DomainBillingFrequency {
    return value as DomainBillingFrequency;
}

