/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DomainBillingMode = {
    BillingModePrepaid: 'prepaid',
    BillingModePostpaid: 'postpaid'
} as const;
export type DomainBillingMode = typeof DomainBillingMode[keyof typeof DomainBillingMode];


export function instanceOfDomainBillingMode(value: any): boolean {
    for (const key in DomainBillingMode) {
        if (Object.prototype.hasOwnProperty.call(DomainBillingMode, key)) {
            if (DomainBillingMode[key as keyof typeof DomainBillingMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DomainBillingModeFromJSON(json: any): DomainBillingMode {
    return DomainBillingModeFromJSONTyped(json, false);
}

export function DomainBillingModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainBillingMode {
    return json as DomainBillingMode;
}

export function DomainBillingModeToJSON(value?: DomainBillingMode | null): any {
    return value as any;
}

export function DomainBillingModeToJSONTyped(value: any, ignoreDiscriminator: boolean): DomainBillingMode {
    return value as DomainBillingMode;
}

