/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainCampaignInfo } from './DomainCampaignInfo';
import {
    DomainCampaignInfoFromJSON,
    DomainCampaignInfoFromJSONTyped,
    DomainCampaignInfoToJSON,
    DomainCampaignInfoToJSONTyped,
} from './DomainCampaignInfo';
import type { DomainDailyStat } from './DomainDailyStat';
import {
    DomainDailyStatFromJSON,
    DomainDailyStatFromJSONTyped,
    DomainDailyStatToJSON,
    DomainDailyStatToJSONTyped,
} from './DomainDailyStat';
import type { DomainCampaignMetrics } from './DomainCampaignMetrics';
import {
    DomainCampaignMetricsFromJSON,
    DomainCampaignMetricsFromJSONTyped,
    DomainCampaignMetricsToJSON,
    DomainCampaignMetricsToJSONTyped,
} from './DomainCampaignMetrics';

/**
 * 
 * @export
 * @interface DomainCampaignDetail
 */
export interface DomainCampaignDetail {
    /**
     * 
     * @type {DomainCampaignInfo}
     * @memberof DomainCampaignDetail
     */
    campaign?: DomainCampaignInfo;
    /**
     * 
     * @type {Array<DomainDailyStat>}
     * @memberof DomainCampaignDetail
     */
    dailyStats?: Array<DomainDailyStat>;
    /**
     * 
     * @type {DomainCampaignMetrics}
     * @memberof DomainCampaignDetail
     */
    performance?: DomainCampaignMetrics;
}

/**
 * Check if a given object implements the DomainCampaignDetail interface.
 */
export function instanceOfDomainCampaignDetail(value: object): value is DomainCampaignDetail {
    return true;
}

export function DomainCampaignDetailFromJSON(json: any): DomainCampaignDetail {
    return DomainCampaignDetailFromJSONTyped(json, false);
}

export function DomainCampaignDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainCampaignDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'campaign': json['campaign'] == null ? undefined : DomainCampaignInfoFromJSON(json['campaign']),
        'dailyStats': json['daily_stats'] == null ? undefined : ((json['daily_stats'] as Array<any>).map(DomainDailyStatFromJSON)),
        'performance': json['performance'] == null ? undefined : DomainCampaignMetricsFromJSON(json['performance']),
    };
}

export function DomainCampaignDetailToJSON(json: any): DomainCampaignDetail {
    return DomainCampaignDetailToJSONTyped(json, false);
}

export function DomainCampaignDetailToJSONTyped(value?: DomainCampaignDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'campaign': DomainCampaignInfoToJSON(value['campaign']),
        'daily_stats': value['dailyStats'] == null ? undefined : ((value['dailyStats'] as Array<any>).map(DomainDailyStatToJSON)),
        'performance': DomainCampaignMetricsToJSON(value['performance']),
    };
}

