/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DomainAssociationType = {
    AssociationTypeInvitation: 'invitation',
    AssociationTypeRequest: 'request'
} as const;
export type DomainAssociationType = typeof DomainAssociationType[keyof typeof DomainAssociationType];


export function instanceOfDomainAssociationType(value: any): boolean {
    for (const key in DomainAssociationType) {
        if (Object.prototype.hasOwnProperty.call(DomainAssociationType, key)) {
            if (DomainAssociationType[key as keyof typeof DomainAssociationType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DomainAssociationTypeFromJSON(json: any): DomainAssociationType {
    return DomainAssociationTypeFromJSONTyped(json, false);
}

export function DomainAssociationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainAssociationType {
    return json as DomainAssociationType;
}

export function DomainAssociationTypeToJSON(value?: DomainAssociationType | null): any {
    return value as any;
}

export function DomainAssociationTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): DomainAssociationType {
    return value as DomainAssociationType;
}

