/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DomainAssociationStatus = {
    AssociationStatusPending: 'pending',
    AssociationStatusActive: 'active',
    AssociationStatusSuspended: 'suspended',
    AssociationStatusRejected: 'rejected'
} as const;
export type DomainAssociationStatus = typeof DomainAssociationStatus[keyof typeof DomainAssociationStatus];


export function instanceOfDomainAssociationStatus(value: any): boolean {
    for (const key in DomainAssociationStatus) {
        if (Object.prototype.hasOwnProperty.call(DomainAssociationStatus, key)) {
            if (DomainAssociationStatus[key as keyof typeof DomainAssociationStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DomainAssociationStatusFromJSON(json: any): DomainAssociationStatus {
    return DomainAssociationStatusFromJSONTyped(json, false);
}

export function DomainAssociationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainAssociationStatus {
    return json as DomainAssociationStatus;
}

export function DomainAssociationStatusToJSON(value?: DomainAssociationStatus | null): any {
    return value as any;
}

export function DomainAssociationStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): DomainAssociationStatus {
    return value as DomainAssociationStatus;
}

