/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainCampaign
 */
export interface DomainCampaign {
    /**
     * 
     * @type {number}
     * @memberof DomainCampaign
     */
    advertiserId?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainCampaign
     */
    campaignId?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainCampaign
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainCampaign
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainCampaign
     */
    endDate?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainCampaign
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainCampaign
     */
    organizationId?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainCampaign
     */
    startDate?: string;
    /**
     * 'draft', 'active', 'paused', 'archived'
     * @type {string}
     * @memberof DomainCampaign
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainCampaign
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the DomainCampaign interface.
 */
export function instanceOfDomainCampaign(value: object): value is DomainCampaign {
    return true;
}

export function DomainCampaignFromJSON(json: any): DomainCampaign {
    return DomainCampaignFromJSONTyped(json, false);
}

export function DomainCampaignFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainCampaign {
    if (json == null) {
        return json;
    }
    return {
        
        'advertiserId': json['advertiser_id'] == null ? undefined : json['advertiser_id'],
        'campaignId': json['campaign_id'] == null ? undefined : json['campaign_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'description': json['description'] == null ? undefined : json['description'],
        'endDate': json['end_date'] == null ? undefined : json['end_date'],
        'name': json['name'] == null ? undefined : json['name'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'startDate': json['start_date'] == null ? undefined : json['start_date'],
        'status': json['status'] == null ? undefined : json['status'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function DomainCampaignToJSON(json: any): DomainCampaign {
    return DomainCampaignToJSONTyped(json, false);
}

export function DomainCampaignToJSONTyped(value?: DomainCampaign | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advertiser_id': value['advertiserId'],
        'campaign_id': value['campaignId'],
        'created_at': value['createdAt'],
        'description': value['description'],
        'end_date': value['endDate'],
        'name': value['name'],
        'organization_id': value['organizationId'],
        'start_date': value['startDate'],
        'status': value['status'],
        'updated_at': value['updatedAt'],
    };
}

