/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainAffiliate
 */
export interface DomainAffiliate {
    /**
     * 
     * @type {number}
     * @memberof DomainAffiliate
     */
    affiliateId?: number;
    /**
     * JSONB stored as string
     * @type {string}
     * @memberof DomainAffiliate
     */
    billingInfo?: string;
    /**
     * JSONB stored as string
     * @type {string}
     * @memberof DomainAffiliate
     */
    contactAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAffiliate
     */
    contactEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAffiliate
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAffiliate
     */
    defaultCurrencyId?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainAffiliate
     */
    defaultPaymentTerms?: number;
    /**
     * General purpose fields moved from EverflowProviderData
     * @type {string}
     * @memberof DomainAffiliate
     */
    internalNotes?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainAffiliate
     */
    invoiceAmountThreshold?: number;
    /**
     * JSONB stored as string (array of strings)
     * @type {string}
     * @memberof DomainAffiliate
     */
    labels?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAffiliate
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainAffiliate
     */
    organizationId?: number;
    /**
     * JSONB stored as string
     * @type {string}
     * @memberof DomainAffiliate
     */
    paymentDetails?: string;
    /**
     * 'active', 'pending', 'rejected', 'inactive'
     * @type {string}
     * @memberof DomainAffiliate
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAffiliate
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the DomainAffiliate interface.
 */
export function instanceOfDomainAffiliate(value: object): value is DomainAffiliate {
    return true;
}

export function DomainAffiliateFromJSON(json: any): DomainAffiliate {
    return DomainAffiliateFromJSONTyped(json, false);
}

export function DomainAffiliateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainAffiliate {
    if (json == null) {
        return json;
    }
    return {
        
        'affiliateId': json['affiliate_id'] == null ? undefined : json['affiliate_id'],
        'billingInfo': json['billing_info'] == null ? undefined : json['billing_info'],
        'contactAddress': json['contact_address'] == null ? undefined : json['contact_address'],
        'contactEmail': json['contact_email'] == null ? undefined : json['contact_email'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'defaultCurrencyId': json['default_currency_id'] == null ? undefined : json['default_currency_id'],
        'defaultPaymentTerms': json['default_payment_terms'] == null ? undefined : json['default_payment_terms'],
        'internalNotes': json['internal_notes'] == null ? undefined : json['internal_notes'],
        'invoiceAmountThreshold': json['invoice_amount_threshold'] == null ? undefined : json['invoice_amount_threshold'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'name': json['name'] == null ? undefined : json['name'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'paymentDetails': json['payment_details'] == null ? undefined : json['payment_details'],
        'status': json['status'] == null ? undefined : json['status'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function DomainAffiliateToJSON(json: any): DomainAffiliate {
    return DomainAffiliateToJSONTyped(json, false);
}

export function DomainAffiliateToJSONTyped(value?: DomainAffiliate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'affiliate_id': value['affiliateId'],
        'billing_info': value['billingInfo'],
        'contact_address': value['contactAddress'],
        'contact_email': value['contactEmail'],
        'created_at': value['createdAt'],
        'default_currency_id': value['defaultCurrencyId'],
        'default_payment_terms': value['defaultPaymentTerms'],
        'internal_notes': value['internalNotes'],
        'invoice_amount_threshold': value['invoiceAmountThreshold'],
        'labels': value['labels'],
        'name': value['name'],
        'organization_id': value['organizationId'],
        'payment_details': value['paymentDetails'],
        'status': value['status'],
        'updated_at': value['updatedAt'],
    };
}

