/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DomainDelegationPermission = {
    PermissionCampaignCreate: 'campaign_create',
    PermissionCampaignManage: 'campaign_manage',
    PermissionCampaignView: 'campaign_view',
    PermissionCampaignDelete: 'campaign_delete',
    PermissionAssociationInvite: 'association_invite',
    PermissionAssociationManage: 'association_manage',
    PermissionAssociationView: 'association_view',
    PermissionInvitationCreate: 'invitation_create',
    PermissionInvitationManage: 'invitation_manage',
    PermissionInvitationView: 'invitation_view',
    PermissionAnalyticsView: 'analytics_view',
    PermissionAnalyticsExport: 'analytics_export',
    PermissionBillingView: 'billing_view',
    PermissionBillingManage: 'billing_manage',
    PermissionOrganizationView: 'organization_view',
    PermissionOrganizationManage: 'organization_manage'
} as const;
export type DomainDelegationPermission = typeof DomainDelegationPermission[keyof typeof DomainDelegationPermission];


export function instanceOfDomainDelegationPermission(value: any): boolean {
    for (const key in DomainDelegationPermission) {
        if (Object.prototype.hasOwnProperty.call(DomainDelegationPermission, key)) {
            if (DomainDelegationPermission[key as keyof typeof DomainDelegationPermission] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DomainDelegationPermissionFromJSON(json: any): DomainDelegationPermission {
    return DomainDelegationPermissionFromJSONTyped(json, false);
}

export function DomainDelegationPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainDelegationPermission {
    return json as DomainDelegationPermission;
}

export function DomainDelegationPermissionToJSON(value?: DomainDelegationPermission | null): any {
    return value as any;
}

export function DomainDelegationPermissionToJSONTyped(value: any, ignoreDiscriminator: boolean): DomainDelegationPermission {
    return value as DomainDelegationPermission;
}

