/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainCreateInvitationRequest
 */
export interface DomainCreateInvitationRequest {
    /**
     * 
     * @type {number}
     * @memberof DomainCreateInvitationRequest
     */
    advertiserOrgId: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof DomainCreateInvitationRequest
     */
    allowedAffiliateOrgIds?: Array<number>;
    /**
     * 
     * @type {boolean}
     * @memberof DomainCreateInvitationRequest
     */
    defaultAllAffiliatesVisible?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DomainCreateInvitationRequest
     */
    defaultAllCampaignsVisible?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof DomainCreateInvitationRequest
     */
    defaultVisibleAffiliateIds?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof DomainCreateInvitationRequest
     */
    defaultVisibleCampaignIds?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof DomainCreateInvitationRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainCreateInvitationRequest
     */
    expiresAt?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainCreateInvitationRequest
     */
    maxUses?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainCreateInvitationRequest
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainCreateInvitationRequest
     */
    name: string;
}

/**
 * Check if a given object implements the DomainCreateInvitationRequest interface.
 */
export function instanceOfDomainCreateInvitationRequest(value: object): value is DomainCreateInvitationRequest {
    if (!('advertiserOrgId' in value) || value['advertiserOrgId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DomainCreateInvitationRequestFromJSON(json: any): DomainCreateInvitationRequest {
    return DomainCreateInvitationRequestFromJSONTyped(json, false);
}

export function DomainCreateInvitationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainCreateInvitationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'advertiserOrgId': json['advertiser_org_id'],
        'allowedAffiliateOrgIds': json['allowed_affiliate_org_ids'] == null ? undefined : json['allowed_affiliate_org_ids'],
        'defaultAllAffiliatesVisible': json['default_all_affiliates_visible'] == null ? undefined : json['default_all_affiliates_visible'],
        'defaultAllCampaignsVisible': json['default_all_campaigns_visible'] == null ? undefined : json['default_all_campaigns_visible'],
        'defaultVisibleAffiliateIds': json['default_visible_affiliate_ids'] == null ? undefined : json['default_visible_affiliate_ids'],
        'defaultVisibleCampaignIds': json['default_visible_campaign_ids'] == null ? undefined : json['default_visible_campaign_ids'],
        'description': json['description'] == null ? undefined : json['description'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'maxUses': json['max_uses'] == null ? undefined : json['max_uses'],
        'message': json['message'] == null ? undefined : json['message'],
        'name': json['name'],
    };
}

export function DomainCreateInvitationRequestToJSON(json: any): DomainCreateInvitationRequest {
    return DomainCreateInvitationRequestToJSONTyped(json, false);
}

export function DomainCreateInvitationRequestToJSONTyped(value?: DomainCreateInvitationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advertiser_org_id': value['advertiserOrgId'],
        'allowed_affiliate_org_ids': value['allowedAffiliateOrgIds'],
        'default_all_affiliates_visible': value['defaultAllAffiliatesVisible'],
        'default_all_campaigns_visible': value['defaultAllCampaignsVisible'],
        'default_visible_affiliate_ids': value['defaultVisibleAffiliateIds'],
        'default_visible_campaign_ids': value['defaultVisibleCampaignIds'],
        'description': value['description'],
        'expires_at': value['expiresAt'],
        'max_uses': value['maxUses'],
        'message': value['message'],
        'name': value['name'],
    };
}

