/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainPublisherConversation } from './DomainPublisherConversation';
import {
    DomainPublisherConversationFromJSON,
    DomainPublisherConversationFromJSONTyped,
    DomainPublisherConversationToJSON,
    DomainPublisherConversationToJSONTyped,
} from './DomainPublisherConversation';
import type { DomainPublisherMessage } from './DomainPublisherMessage';
import {
    DomainPublisherMessageFromJSON,
    DomainPublisherMessageFromJSONTyped,
    DomainPublisherMessageToJSON,
    DomainPublisherMessageToJSONTyped,
} from './DomainPublisherMessage';

/**
 * 
 * @export
 * @interface DomainConversationWithMessagesResponse
 */
export interface DomainConversationWithMessagesResponse {
    /**
     * 
     * @type {DomainPublisherConversation}
     * @memberof DomainConversationWithMessagesResponse
     */
    conversation?: DomainPublisherConversation;
    /**
     * 
     * @type {Array<DomainPublisherMessage>}
     * @memberof DomainConversationWithMessagesResponse
     */
    messages?: Array<DomainPublisherMessage>;
    /**
     * 
     * @type {number}
     * @memberof DomainConversationWithMessagesResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainConversationWithMessagesResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainConversationWithMessagesResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the DomainConversationWithMessagesResponse interface.
 */
export function instanceOfDomainConversationWithMessagesResponse(value: object): value is DomainConversationWithMessagesResponse {
    return true;
}

export function DomainConversationWithMessagesResponseFromJSON(json: any): DomainConversationWithMessagesResponse {
    return DomainConversationWithMessagesResponseFromJSONTyped(json, false);
}

export function DomainConversationWithMessagesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainConversationWithMessagesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'conversation': json['conversation'] == null ? undefined : DomainPublisherConversationFromJSON(json['conversation']),
        'messages': json['messages'] == null ? undefined : ((json['messages'] as Array<any>).map(DomainPublisherMessageFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function DomainConversationWithMessagesResponseToJSON(json: any): DomainConversationWithMessagesResponse {
    return DomainConversationWithMessagesResponseToJSONTyped(json, false);
}

export function DomainConversationWithMessagesResponseToJSONTyped(value?: DomainConversationWithMessagesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversation': DomainPublisherConversationToJSON(value['conversation']),
        'messages': value['messages'] == null ? undefined : ((value['messages'] as Array<any>).map(DomainPublisherMessageToJSON)),
        'page': value['page'],
        'page_size': value['pageSize'],
        'total': value['total'],
    };
}

