/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainKeywordDataSampleValueInner
 */
export interface DomainKeywordDataSampleValueInner {
    /**
     * 
     * @type {number}
     * @memberof DomainKeywordDataSampleValueInner
     */
    score?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainKeywordDataSampleValueInner
     */
    value?: string;
}

/**
 * Check if a given object implements the DomainKeywordDataSampleValueInner interface.
 */
export function instanceOfDomainKeywordDataSampleValueInner(value: object): value is DomainKeywordDataSampleValueInner {
    return true;
}

export function DomainKeywordDataSampleValueInnerFromJSON(json: any): DomainKeywordDataSampleValueInner {
    return DomainKeywordDataSampleValueInnerFromJSONTyped(json, false);
}

export function DomainKeywordDataSampleValueInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainKeywordDataSampleValueInner {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'] == null ? undefined : json['score'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function DomainKeywordDataSampleValueInnerToJSON(json: any): DomainKeywordDataSampleValueInner {
    return DomainKeywordDataSampleValueInnerToJSONTyped(json, false);
}

export function DomainKeywordDataSampleValueInnerToJSONTyped(value?: DomainKeywordDataSampleValueInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': value['score'],
        'value': value['value'],
    };
}

