/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainPaginationResult
 */
export interface DomainPaginationResult {
    /**
     * 
     * @type {number}
     * @memberof DomainPaginationResult
     */
    currentPage?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DomainPaginationResult
     */
    hasNextPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DomainPaginationResult
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DomainPaginationResult
     */
    itemsPerPage?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainPaginationResult
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainPaginationResult
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the DomainPaginationResult interface.
 */
export function instanceOfDomainPaginationResult(value: object): value is DomainPaginationResult {
    return true;
}

export function DomainPaginationResultFromJSON(json: any): DomainPaginationResult {
    return DomainPaginationResultFromJSONTyped(json, false);
}

export function DomainPaginationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainPaginationResult {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['current_page'] == null ? undefined : json['current_page'],
        'hasNextPage': json['has_next_page'] == null ? undefined : json['has_next_page'],
        'hasPreviousPage': json['has_previous_page'] == null ? undefined : json['has_previous_page'],
        'itemsPerPage': json['items_per_page'] == null ? undefined : json['items_per_page'],
        'totalItems': json['total_items'] == null ? undefined : json['total_items'],
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
    };
}

export function DomainPaginationResultToJSON(json: any): DomainPaginationResult {
    return DomainPaginationResultToJSONTyped(json, false);
}

export function DomainPaginationResultToJSONTyped(value?: DomainPaginationResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_page': value['currentPage'],
        'has_next_page': value['hasNextPage'],
        'has_previous_page': value['hasPreviousPage'],
        'items_per_page': value['itemsPerPage'],
        'total_items': value['totalItems'],
        'total_pages': value['totalPages'],
    };
}

