/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainCampaignMetrics
 */
export interface DomainCampaignMetrics {
    /**
     * 
     * @type {number}
     * @memberof DomainCampaignMetrics
     */
    clicks?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainCampaignMetrics
     */
    conversions?: number;
    /**
     * Cost per acquisition
     * @type {number}
     * @memberof DomainCampaignMetrics
     */
    cpa?: number;
    /**
     * Cost per click
     * @type {number}
     * @memberof DomainCampaignMetrics
     */
    cpc?: number;
    /**
     * Click-through rate
     * @type {number}
     * @memberof DomainCampaignMetrics
     */
    ctr?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainCampaignMetrics
     */
    impressions?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainCampaignMetrics
     */
    revenue?: number;
}

/**
 * Check if a given object implements the DomainCampaignMetrics interface.
 */
export function instanceOfDomainCampaignMetrics(value: object): value is DomainCampaignMetrics {
    return true;
}

export function DomainCampaignMetricsFromJSON(json: any): DomainCampaignMetrics {
    return DomainCampaignMetricsFromJSONTyped(json, false);
}

export function DomainCampaignMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainCampaignMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'clicks': json['clicks'] == null ? undefined : json['clicks'],
        'conversions': json['conversions'] == null ? undefined : json['conversions'],
        'cpa': json['cpa'] == null ? undefined : json['cpa'],
        'cpc': json['cpc'] == null ? undefined : json['cpc'],
        'ctr': json['ctr'] == null ? undefined : json['ctr'],
        'impressions': json['impressions'] == null ? undefined : json['impressions'],
        'revenue': json['revenue'] == null ? undefined : json['revenue'],
    };
}

export function DomainCampaignMetricsToJSON(json: any): DomainCampaignMetrics {
    return DomainCampaignMetricsToJSONTyped(json, false);
}

export function DomainCampaignMetricsToJSONTyped(value?: DomainCampaignMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clicks': value['clicks'],
        'conversions': value['conversions'],
        'cpa': value['cpa'],
        'cpc': value['cpc'],
        'ctr': value['ctr'],
        'impressions': value['impressions'],
        'revenue': value['revenue'],
    };
}

