/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DomainOrganizationType = {
    OrganizationTypeAdvertiser: 'advertiser',
    OrganizationTypeAffiliate: 'affiliate',
    OrganizationTypePlatformOwner: 'platform_owner'
} as const;
export type DomainOrganizationType = typeof DomainOrganizationType[keyof typeof DomainOrganizationType];


export function instanceOfDomainOrganizationType(value: any): boolean {
    for (const key in DomainOrganizationType) {
        if (Object.prototype.hasOwnProperty.call(DomainOrganizationType, key)) {
            if (DomainOrganizationType[key as keyof typeof DomainOrganizationType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DomainOrganizationTypeFromJSON(json: any): DomainOrganizationType {
    return DomainOrganizationTypeFromJSONTyped(json, false);
}

export function DomainOrganizationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainOrganizationType {
    return json as DomainOrganizationType;
}

export function DomainOrganizationTypeToJSON(value?: DomainOrganizationType | null): any {
    return value as any;
}

export function DomainOrganizationTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): DomainOrganizationType {
    return value as DomainOrganizationType;
}

