/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainDailyStat
 */
export interface DomainDailyStat {
    /**
     * 
     * @type {number}
     * @memberof DomainDailyStat
     */
    clicks?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainDailyStat
     */
    conversions?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainDailyStat
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainDailyStat
     */
    impressions?: number;
    /**
     * 
     * @type {number}
     * @memberof DomainDailyStat
     */
    revenue?: number;
}

/**
 * Check if a given object implements the DomainDailyStat interface.
 */
export function instanceOfDomainDailyStat(value: object): value is DomainDailyStat {
    return true;
}

export function DomainDailyStatFromJSON(json: any): DomainDailyStat {
    return DomainDailyStatFromJSONTyped(json, false);
}

export function DomainDailyStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainDailyStat {
    if (json == null) {
        return json;
    }
    return {
        
        'clicks': json['clicks'] == null ? undefined : json['clicks'],
        'conversions': json['conversions'] == null ? undefined : json['conversions'],
        'date': json['date'] == null ? undefined : json['date'],
        'impressions': json['impressions'] == null ? undefined : json['impressions'],
        'revenue': json['revenue'] == null ? undefined : json['revenue'],
    };
}

export function DomainDailyStatToJSON(json: any): DomainDailyStat {
    return DomainDailyStatToJSONTyped(json, false);
}

export function DomainDailyStatToJSONTyped(value?: DomainDailyStat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clicks': value['clicks'],
        'conversions': value['conversions'],
        'date': value['date'],
        'impressions': value['impressions'],
        'revenue': value['revenue'],
    };
}

