/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainMetaData
 */
export interface DomainMetaData {
    /**
     * 
     * @type {string}
     * @memberof DomainMetaData
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainMetaData
     */
    faviconImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainMetaData
     */
    screenshotImageUrl?: string;
}

/**
 * Check if a given object implements the DomainMetaData interface.
 */
export function instanceOfDomainMetaData(value: object): value is DomainMetaData {
    return true;
}

export function DomainMetaDataFromJSON(json: any): DomainMetaData {
    return DomainMetaDataFromJSONTyped(json, false);
}

export function DomainMetaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainMetaData {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'faviconImageUrl': json['faviconImageUrl'] == null ? undefined : json['faviconImageUrl'],
        'screenshotImageUrl': json['screenshotImageUrl'] == null ? undefined : json['screenshotImageUrl'],
    };
}

export function DomainMetaDataToJSON(json: any): DomainMetaData {
    return DomainMetaDataToJSONTyped(json, false);
}

export function DomainMetaDataToJSONTyped(value?: DomainMetaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'faviconImageUrl': value['faviconImageUrl'],
        'screenshotImageUrl': value['screenshotImageUrl'],
    };
}

