/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainAssociationStatus } from './DomainAssociationStatus';
import {
    DomainAssociationStatusFromJSON,
    DomainAssociationStatusFromJSONTyped,
    DomainAssociationStatusToJSON,
    DomainAssociationStatusToJSONTyped,
} from './DomainAssociationStatus';

/**
 * 
 * @export
 * @interface DomainUpdateAssociationRequest
 */
export interface DomainUpdateAssociationRequest {
    /**
     * 
     * @type {boolean}
     * @memberof DomainUpdateAssociationRequest
     */
    allAffiliatesVisible?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DomainUpdateAssociationRequest
     */
    allCampaignsVisible?: boolean;
    /**
     * 
     * @type {DomainAssociationStatus}
     * @memberof DomainUpdateAssociationRequest
     */
    status?: DomainAssociationStatus;
    /**
     * 
     * @type {Array<number>}
     * @memberof DomainUpdateAssociationRequest
     */
    visibleAffiliateIds?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof DomainUpdateAssociationRequest
     */
    visibleCampaignIds?: Array<number>;
}



/**
 * Check if a given object implements the DomainUpdateAssociationRequest interface.
 */
export function instanceOfDomainUpdateAssociationRequest(value: object): value is DomainUpdateAssociationRequest {
    return true;
}

export function DomainUpdateAssociationRequestFromJSON(json: any): DomainUpdateAssociationRequest {
    return DomainUpdateAssociationRequestFromJSONTyped(json, false);
}

export function DomainUpdateAssociationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainUpdateAssociationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'allAffiliatesVisible': json['all_affiliates_visible'] == null ? undefined : json['all_affiliates_visible'],
        'allCampaignsVisible': json['all_campaigns_visible'] == null ? undefined : json['all_campaigns_visible'],
        'status': json['status'] == null ? undefined : DomainAssociationStatusFromJSON(json['status']),
        'visibleAffiliateIds': json['visible_affiliate_ids'] == null ? undefined : json['visible_affiliate_ids'],
        'visibleCampaignIds': json['visible_campaign_ids'] == null ? undefined : json['visible_campaign_ids'],
    };
}

export function DomainUpdateAssociationRequestToJSON(json: any): DomainUpdateAssociationRequest {
    return DomainUpdateAssociationRequestToJSONTyped(json, false);
}

export function DomainUpdateAssociationRequestToJSONTyped(value?: DomainUpdateAssociationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'all_affiliates_visible': value['allAffiliatesVisible'],
        'all_campaigns_visible': value['allCampaignsVisible'],
        'status': DomainAssociationStatusToJSON(value['status']),
        'visible_affiliate_ids': value['visibleAffiliateIds'],
        'visible_campaign_ids': value['visibleCampaignIds'],
    };
}

