/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainInvitationStatus } from './DomainInvitationStatus';
import {
    DomainInvitationStatusFromJSON,
    DomainInvitationStatusFromJSONTyped,
    DomainInvitationStatusToJSON,
    DomainInvitationStatusToJSONTyped,
} from './DomainInvitationStatus';
import type { DomainProfile } from './DomainProfile';
import {
    DomainProfileFromJSON,
    DomainProfileFromJSONTyped,
    DomainProfileToJSON,
    DomainProfileToJSONTyped,
} from './DomainProfile';
import type { DomainInvitationUsageLog } from './DomainInvitationUsageLog';
import {
    DomainInvitationUsageLogFromJSON,
    DomainInvitationUsageLogFromJSONTyped,
    DomainInvitationUsageLogToJSON,
    DomainInvitationUsageLogToJSONTyped,
} from './DomainInvitationUsageLog';
import type { DomainOrganization } from './DomainOrganization';
import {
    DomainOrganizationFromJSON,
    DomainOrganizationFromJSONTyped,
    DomainOrganizationToJSON,
    DomainOrganizationToJSONTyped,
} from './DomainOrganization';

/**
 * 
 * @export
 * @interface DomainAdvertiserAssociationInvitationWithDetails
 */
export interface DomainAdvertiserAssociationInvitationWithDetails {
    /**
     * 
     * @type {number}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    advertiserOrgId?: number;
    /**
     * 
     * @type {DomainOrganization}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    advertiserOrganization?: DomainOrganization;
    /**
     * Access control
     * @type {string}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    allowedAffiliateOrgIds?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    createdAt?: string;
    /**
     * 
     * @type {DomainProfile}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    createdByUser?: DomainProfile;
    /**
     * 
     * @type {string}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    createdByUserId?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    currentUses?: number;
    /**
     * Default visibility settings for associations created through this invitation
     * @type {boolean}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    defaultAllAffiliatesVisible?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    defaultAllCampaignsVisible?: boolean;
    /**
     * JSONB array
     * @type {string}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    defaultVisibleAffiliateIds?: string;
    /**
     * JSONB array
     * @type {string}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    defaultVisibleCampaignIds?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    description?: string;
    /**
     * Expiration
     * @type {string}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    expiresAt?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    invitationId?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    invitationToken?: string;
    /**
     * Usage limits
     * @type {number}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    maxUses?: number;
    /**
     * 
     * @type {string}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    name?: string;
    /**
     * 
     * @type {Array<DomainInvitationUsageLog>}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    recentUsages?: Array<DomainInvitationUsageLog>;
    /**
     * Status and metadata
     * @type {DomainInvitationStatus}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    status?: DomainInvitationStatus;
    /**
     * 
     * @type {string}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof DomainAdvertiserAssociationInvitationWithDetails
     */
    usageCount?: number;
}



/**
 * Check if a given object implements the DomainAdvertiserAssociationInvitationWithDetails interface.
 */
export function instanceOfDomainAdvertiserAssociationInvitationWithDetails(value: object): value is DomainAdvertiserAssociationInvitationWithDetails {
    return true;
}

export function DomainAdvertiserAssociationInvitationWithDetailsFromJSON(json: any): DomainAdvertiserAssociationInvitationWithDetails {
    return DomainAdvertiserAssociationInvitationWithDetailsFromJSONTyped(json, false);
}

export function DomainAdvertiserAssociationInvitationWithDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainAdvertiserAssociationInvitationWithDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'advertiserOrgId': json['advertiser_org_id'] == null ? undefined : json['advertiser_org_id'],
        'advertiserOrganization': json['advertiser_organization'] == null ? undefined : DomainOrganizationFromJSON(json['advertiser_organization']),
        'allowedAffiliateOrgIds': json['allowed_affiliate_org_ids'] == null ? undefined : json['allowed_affiliate_org_ids'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'createdByUser': json['created_by_user'] == null ? undefined : DomainProfileFromJSON(json['created_by_user']),
        'createdByUserId': json['created_by_user_id'] == null ? undefined : json['created_by_user_id'],
        'currentUses': json['current_uses'] == null ? undefined : json['current_uses'],
        'defaultAllAffiliatesVisible': json['default_all_affiliates_visible'] == null ? undefined : json['default_all_affiliates_visible'],
        'defaultAllCampaignsVisible': json['default_all_campaigns_visible'] == null ? undefined : json['default_all_campaigns_visible'],
        'defaultVisibleAffiliateIds': json['default_visible_affiliate_ids'] == null ? undefined : json['default_visible_affiliate_ids'],
        'defaultVisibleCampaignIds': json['default_visible_campaign_ids'] == null ? undefined : json['default_visible_campaign_ids'],
        'description': json['description'] == null ? undefined : json['description'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'invitationId': json['invitation_id'] == null ? undefined : json['invitation_id'],
        'invitationToken': json['invitation_token'] == null ? undefined : json['invitation_token'],
        'maxUses': json['max_uses'] == null ? undefined : json['max_uses'],
        'message': json['message'] == null ? undefined : json['message'],
        'name': json['name'] == null ? undefined : json['name'],
        'recentUsages': json['recent_usages'] == null ? undefined : ((json['recent_usages'] as Array<any>).map(DomainInvitationUsageLogFromJSON)),
        'status': json['status'] == null ? undefined : DomainInvitationStatusFromJSON(json['status']),
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'usageCount': json['usage_count'] == null ? undefined : json['usage_count'],
    };
}

export function DomainAdvertiserAssociationInvitationWithDetailsToJSON(json: any): DomainAdvertiserAssociationInvitationWithDetails {
    return DomainAdvertiserAssociationInvitationWithDetailsToJSONTyped(json, false);
}

export function DomainAdvertiserAssociationInvitationWithDetailsToJSONTyped(value?: DomainAdvertiserAssociationInvitationWithDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advertiser_org_id': value['advertiserOrgId'],
        'advertiser_organization': DomainOrganizationToJSON(value['advertiserOrganization']),
        'allowed_affiliate_org_ids': value['allowedAffiliateOrgIds'],
        'created_at': value['createdAt'],
        'created_by_user': DomainProfileToJSON(value['createdByUser']),
        'created_by_user_id': value['createdByUserId'],
        'current_uses': value['currentUses'],
        'default_all_affiliates_visible': value['defaultAllAffiliatesVisible'],
        'default_all_campaigns_visible': value['defaultAllCampaignsVisible'],
        'default_visible_affiliate_ids': value['defaultVisibleAffiliateIds'],
        'default_visible_campaign_ids': value['defaultVisibleCampaignIds'],
        'description': value['description'],
        'expires_at': value['expiresAt'],
        'invitation_id': value['invitationId'],
        'invitation_token': value['invitationToken'],
        'max_uses': value['maxUses'],
        'message': value['message'],
        'name': value['name'],
        'recent_usages': value['recentUsages'] == null ? undefined : ((value['recentUsages'] as Array<any>).map(DomainInvitationUsageLogToJSON)),
        'status': DomainInvitationStatusToJSON(value['status']),
        'updated_at': value['updatedAt'],
        'usage_count': value['usageCount'],
    };
}

