/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersCreateAffiliateProviderMappingRequest
 */
export interface HandlersCreateAffiliateProviderMappingRequest {
    /**
     * Affiliate ID
     * @type {number}
     * @memberof HandlersCreateAffiliateProviderMappingRequest
     */
    affiliateId: number;
    /**
     * Provider's affiliate ID
     * @type {string}
     * @memberof HandlersCreateAffiliateProviderMappingRequest
     */
    providerAffiliateId?: string;
    /**
     * Provider configuration in JSON format
     * swagger:strfmt json
     * @type {object}
     * @memberof HandlersCreateAffiliateProviderMappingRequest
     */
    providerConfig?: object;
    /**
     * Provider type (e.g., 'everflow')
     * @type {string}
     * @memberof HandlersCreateAffiliateProviderMappingRequest
     */
    providerType: string;
}

/**
 * Check if a given object implements the HandlersCreateAffiliateProviderMappingRequest interface.
 */
export function instanceOfHandlersCreateAffiliateProviderMappingRequest(value: object): value is HandlersCreateAffiliateProviderMappingRequest {
    if (!('affiliateId' in value) || value['affiliateId'] === undefined) return false;
    if (!('providerType' in value) || value['providerType'] === undefined) return false;
    return true;
}

export function HandlersCreateAffiliateProviderMappingRequestFromJSON(json: any): HandlersCreateAffiliateProviderMappingRequest {
    return HandlersCreateAffiliateProviderMappingRequestFromJSONTyped(json, false);
}

export function HandlersCreateAffiliateProviderMappingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersCreateAffiliateProviderMappingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'affiliateId': json['affiliate_id'],
        'providerAffiliateId': json['provider_affiliate_id'] == null ? undefined : json['provider_affiliate_id'],
        'providerConfig': json['provider_config'] == null ? undefined : json['provider_config'],
        'providerType': json['provider_type'],
    };
}

export function HandlersCreateAffiliateProviderMappingRequestToJSON(json: any): HandlersCreateAffiliateProviderMappingRequest {
    return HandlersCreateAffiliateProviderMappingRequestToJSONTyped(json, false);
}

export function HandlersCreateAffiliateProviderMappingRequestToJSONTyped(value?: HandlersCreateAffiliateProviderMappingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'affiliate_id': value['affiliateId'],
        'provider_affiliate_id': value['providerAffiliateId'],
        'provider_config': value['providerConfig'],
        'provider_type': value['providerType'],
    };
}

