/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersDateRangeInfo
 */
export interface HandlersDateRangeInfo {
    /**
     * 
     * @type {string}
     * @memberof HandlersDateRangeInfo
     */
    endDate?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersDateRangeInfo
     */
    startDate?: string;
}

/**
 * Check if a given object implements the HandlersDateRangeInfo interface.
 */
export function instanceOfHandlersDateRangeInfo(value: object): value is HandlersDateRangeInfo {
    return true;
}

export function HandlersDateRangeInfoFromJSON(json: any): HandlersDateRangeInfo {
    return HandlersDateRangeInfoFromJSONTyped(json, false);
}

export function HandlersDateRangeInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersDateRangeInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'endDate': json['endDate'] == null ? undefined : json['endDate'],
        'startDate': json['startDate'] == null ? undefined : json['startDate'],
    };
}

export function HandlersDateRangeInfoToJSON(json: any): HandlersDateRangeInfo {
    return HandlersDateRangeInfoToJSONTyped(json, false);
}

export function HandlersDateRangeInfoToJSONTyped(value?: HandlersDateRangeInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endDate': value['endDate'],
        'startDate': value['startDate'],
    };
}

