/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainCampaignListItem } from './DomainCampaignListItem';
import {
    DomainCampaignListItemFromJSON,
    DomainCampaignListItemFromJSONTyped,
    DomainCampaignListItemToJSON,
    DomainCampaignListItemToJSONTyped,
} from './DomainCampaignListItem';

/**
 * 
 * @export
 * @interface HandlersCampaignsListResponse
 */
export interface HandlersCampaignsListResponse {
    /**
     * 
     * @type {Array<DomainCampaignListItem>}
     * @memberof HandlersCampaignsListResponse
     */
    data?: Array<DomainCampaignListItem>;
    /**
     * 
     * @type {string}
     * @memberof HandlersCampaignsListResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the HandlersCampaignsListResponse interface.
 */
export function instanceOfHandlersCampaignsListResponse(value: object): value is HandlersCampaignsListResponse {
    return true;
}

export function HandlersCampaignsListResponseFromJSON(json: any): HandlersCampaignsListResponse {
    return HandlersCampaignsListResponseFromJSONTyped(json, false);
}

export function HandlersCampaignsListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersCampaignsListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DomainCampaignListItemFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function HandlersCampaignsListResponseToJSON(json: any): HandlersCampaignsListResponse {
    return HandlersCampaignsListResponseToJSONTyped(json, false);
}

export function HandlersCampaignsListResponseToJSONTyped(value?: HandlersCampaignsListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DomainCampaignListItemToJSON)),
        'status': value['status'],
    };
}

