/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersCreateCampaignProviderOfferRequest
 */
export interface HandlersCreateCampaignProviderOfferRequest {
    /**
     * Campaign ID
     * @type {number}
     * @memberof HandlersCreateCampaignProviderOfferRequest
     */
    campaignId: number;
    /**
     * Whether the offer is active on the provider
     * @type {boolean}
     * @memberof HandlersCreateCampaignProviderOfferRequest
     */
    isActiveOnProvider?: boolean;
    /**
     * Provider offer configuration in JSON format
     * swagger:strfmt json
     * @type {object}
     * @memberof HandlersCreateCampaignProviderOfferRequest
     */
    providerOfferConfig?: object;
    /**
     * Provider's offer reference
     * @type {string}
     * @memberof HandlersCreateCampaignProviderOfferRequest
     */
    providerOfferRef?: string;
    /**
     * Provider type (e.g., 'everflow')
     * @type {string}
     * @memberof HandlersCreateCampaignProviderOfferRequest
     */
    providerType: string;
}

/**
 * Check if a given object implements the HandlersCreateCampaignProviderOfferRequest interface.
 */
export function instanceOfHandlersCreateCampaignProviderOfferRequest(value: object): value is HandlersCreateCampaignProviderOfferRequest {
    if (!('campaignId' in value) || value['campaignId'] === undefined) return false;
    if (!('providerType' in value) || value['providerType'] === undefined) return false;
    return true;
}

export function HandlersCreateCampaignProviderOfferRequestFromJSON(json: any): HandlersCreateCampaignProviderOfferRequest {
    return HandlersCreateCampaignProviderOfferRequestFromJSONTyped(json, false);
}

export function HandlersCreateCampaignProviderOfferRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersCreateCampaignProviderOfferRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'campaignId': json['campaign_id'],
        'isActiveOnProvider': json['is_active_on_provider'] == null ? undefined : json['is_active_on_provider'],
        'providerOfferConfig': json['provider_offer_config'] == null ? undefined : json['provider_offer_config'],
        'providerOfferRef': json['provider_offer_ref'] == null ? undefined : json['provider_offer_ref'],
        'providerType': json['provider_type'],
    };
}

export function HandlersCreateCampaignProviderOfferRequestToJSON(json: any): HandlersCreateCampaignProviderOfferRequest {
    return HandlersCreateCampaignProviderOfferRequestToJSONTyped(json, false);
}

export function HandlersCreateCampaignProviderOfferRequestToJSONTyped(value?: HandlersCreateCampaignProviderOfferRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'campaign_id': value['campaignId'],
        'is_active_on_provider': value['isActiveOnProvider'],
        'provider_offer_config': value['providerOfferConfig'],
        'provider_offer_ref': value['providerOfferRef'],
        'provider_type': value['providerType'],
    };
}

