/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersCreatePublisherRequest
 */
export interface HandlersCreatePublisherRequest {
    /**
     * 
     * @type {{ [key: string]: any | undefined; }}
     * @memberof HandlersCreatePublisherRequest
     */
    data: { [key: string]: any | undefined; };
    /**
     * 
     * @type {string}
     * @memberof HandlersCreatePublisherRequest
     */
    domain: string;
}

/**
 * Check if a given object implements the HandlersCreatePublisherRequest interface.
 */
export function instanceOfHandlersCreatePublisherRequest(value: object): value is HandlersCreatePublisherRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    return true;
}

export function HandlersCreatePublisherRequestFromJSON(json: any): HandlersCreatePublisherRequest {
    return HandlersCreatePublisherRequestFromJSONTyped(json, false);
}

export function HandlersCreatePublisherRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersCreatePublisherRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'domain': json['domain'],
    };
}

export function HandlersCreatePublisherRequestToJSON(json: any): HandlersCreatePublisherRequest {
    return HandlersCreatePublisherRequestToJSONTyped(json, false);
}

export function HandlersCreatePublisherRequestToJSONTyped(value?: HandlersCreatePublisherRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'domain': value['domain'],
    };
}

