/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersCreateOrganizationRequest
 */
export interface HandlersCreateOrganizationRequest {
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateOrganizationRequest
     */
    name: string;
}

/**
 * Check if a given object implements the HandlersCreateOrganizationRequest interface.
 */
export function instanceOfHandlersCreateOrganizationRequest(value: object): value is HandlersCreateOrganizationRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function HandlersCreateOrganizationRequestFromJSON(json: any): HandlersCreateOrganizationRequest {
    return HandlersCreateOrganizationRequestFromJSONTyped(json, false);
}

export function HandlersCreateOrganizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersCreateOrganizationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function HandlersCreateOrganizationRequestToJSON(json: any): HandlersCreateOrganizationRequest {
    return HandlersCreateOrganizationRequestToJSONTyped(json, false);
}

export function HandlersCreateOrganizationRequestToJSONTyped(value?: HandlersCreateOrganizationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

