/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainPaginationResult } from './DomainPaginationResult';
import {
    DomainPaginationResultFromJSON,
    DomainPaginationResultFromJSONTyped,
    DomainPaginationResultToJSON,
    DomainPaginationResultToJSONTyped,
} from './DomainPaginationResult';
import type { DomainConversionReport } from './DomainConversionReport';
import {
    DomainConversionReportFromJSON,
    DomainConversionReportFromJSONTyped,
    DomainConversionReportToJSON,
    DomainConversionReportToJSONTyped,
} from './DomainConversionReport';

/**
 * 
 * @export
 * @interface HandlersConversionsReportResponse
 */
export interface HandlersConversionsReportResponse {
    /**
     * 
     * @type {Array<DomainConversionReport>}
     * @memberof HandlersConversionsReportResponse
     */
    data?: Array<DomainConversionReport>;
    /**
     * 
     * @type {DomainPaginationResult}
     * @memberof HandlersConversionsReportResponse
     */
    pagination?: DomainPaginationResult;
    /**
     * 
     * @type {string}
     * @memberof HandlersConversionsReportResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the HandlersConversionsReportResponse interface.
 */
export function instanceOfHandlersConversionsReportResponse(value: object): value is HandlersConversionsReportResponse {
    return true;
}

export function HandlersConversionsReportResponseFromJSON(json: any): HandlersConversionsReportResponse {
    return HandlersConversionsReportResponseFromJSONTyped(json, false);
}

export function HandlersConversionsReportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersConversionsReportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DomainConversionReportFromJSON)),
        'pagination': json['pagination'] == null ? undefined : DomainPaginationResultFromJSON(json['pagination']),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function HandlersConversionsReportResponseToJSON(json: any): HandlersConversionsReportResponse {
    return HandlersConversionsReportResponseToJSONTyped(json, false);
}

export function HandlersConversionsReportResponseToJSONTyped(value?: HandlersConversionsReportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DomainConversionReportToJSON)),
        'pagination': DomainPaginationResultToJSON(value['pagination']),
        'status': value['status'],
    };
}

