/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainDelegationPermission } from './DomainDelegationPermission';
import {
    DomainDelegationPermissionFromJSON,
    DomainDelegationPermissionFromJSONTyped,
    DomainDelegationPermissionToJSON,
    DomainDelegationPermissionToJSONTyped,
} from './DomainDelegationPermission';

/**
 * 
 * @export
 * @interface HandlersUpdatePermissionsRequest
 */
export interface HandlersUpdatePermissionsRequest {
    /**
     * 
     * @type {Array<DomainDelegationPermission>}
     * @memberof HandlersUpdatePermissionsRequest
     */
    permissions: Array<DomainDelegationPermission>;
}

/**
 * Check if a given object implements the HandlersUpdatePermissionsRequest interface.
 */
export function instanceOfHandlersUpdatePermissionsRequest(value: object): value is HandlersUpdatePermissionsRequest {
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function HandlersUpdatePermissionsRequestFromJSON(json: any): HandlersUpdatePermissionsRequest {
    return HandlersUpdatePermissionsRequestFromJSONTyped(json, false);
}

export function HandlersUpdatePermissionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersUpdatePermissionsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'permissions': ((json['permissions'] as Array<any>).map(DomainDelegationPermissionFromJSON)),
    };
}

export function HandlersUpdatePermissionsRequestToJSON(json: any): HandlersUpdatePermissionsRequest {
    return HandlersUpdatePermissionsRequestToJSONTyped(json, false);
}

export function HandlersUpdatePermissionsRequestToJSONTyped(value?: HandlersUpdatePermissionsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permissions': ((value['permissions'] as Array<any>).map(DomainDelegationPermissionToJSON)),
    };
}

