/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersUpdateExpirationRequest
 */
export interface HandlersUpdateExpirationRequest {
    /**
     * 
     * @type {string}
     * @memberof HandlersUpdateExpirationRequest
     */
    expiresAt?: string;
}

/**
 * Check if a given object implements the HandlersUpdateExpirationRequest interface.
 */
export function instanceOfHandlersUpdateExpirationRequest(value: object): value is HandlersUpdateExpirationRequest {
    return true;
}

export function HandlersUpdateExpirationRequestFromJSON(json: any): HandlersUpdateExpirationRequest {
    return HandlersUpdateExpirationRequestFromJSONTyped(json, false);
}

export function HandlersUpdateExpirationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersUpdateExpirationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
    };
}

export function HandlersUpdateExpirationRequestToJSON(json: any): HandlersUpdateExpirationRequest {
    return HandlersUpdateExpirationRequestToJSONTyped(json, false);
}

export function HandlersUpdateExpirationRequestToJSONTyped(value?: HandlersUpdateExpirationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expires_at': value['expiresAt'],
    };
}

