/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersCreateAdvertiserRequest
 */
export interface HandlersCreateAdvertiserRequest {
    /**
     * Billing details in JSON format
     * swagger:strfmt json
     * @type {object}
     * @memberof HandlersCreateAdvertiserRequest
     */
    billingDetails?: object;
    /**
     * Contact email address
     * @type {string}
     * @memberof HandlersCreateAdvertiserRequest
     */
    contactEmail?: string;
    /**
     * Advertiser name
     * @type {string}
     * @memberof HandlersCreateAdvertiserRequest
     */
    name: string;
    /**
     * Organization ID
     * @type {number}
     * @memberof HandlersCreateAdvertiserRequest
     */
    organizationId: number;
    /**
     * Status of the advertiser (active, pending, inactive, rejected)
     * @type {string}
     * @memberof HandlersCreateAdvertiserRequest
     */
    status?: string;
}

/**
 * Check if a given object implements the HandlersCreateAdvertiserRequest interface.
 */
export function instanceOfHandlersCreateAdvertiserRequest(value: object): value is HandlersCreateAdvertiserRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    return true;
}

export function HandlersCreateAdvertiserRequestFromJSON(json: any): HandlersCreateAdvertiserRequest {
    return HandlersCreateAdvertiserRequestFromJSONTyped(json, false);
}

export function HandlersCreateAdvertiserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersCreateAdvertiserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'billingDetails': json['billing_details'] == null ? undefined : json['billing_details'],
        'contactEmail': json['contact_email'] == null ? undefined : json['contact_email'],
        'name': json['name'],
        'organizationId': json['organization_id'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function HandlersCreateAdvertiserRequestToJSON(json: any): HandlersCreateAdvertiserRequest {
    return HandlersCreateAdvertiserRequestToJSONTyped(json, false);
}

export function HandlersCreateAdvertiserRequestToJSONTyped(value?: HandlersCreateAdvertiserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'billing_details': value['billingDetails'],
        'contact_email': value['contactEmail'],
        'name': value['name'],
        'organization_id': value['organizationId'],
        'status': value['status'],
    };
}

