/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersCreateCampaignRequest
 */
export interface HandlersCreateCampaignRequest {
    /**
     * 
     * @type {number}
     * @memberof HandlersCreateCampaignRequest
     */
    advertiserId: number;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateCampaignRequest
     */
    description?: string;
    /**
     * Format: YYYY-MM-DD
     * @type {string}
     * @memberof HandlersCreateCampaignRequest
     */
    endDate?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateCampaignRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof HandlersCreateCampaignRequest
     */
    organizationId: number;
    /**
     * Format: YYYY-MM-DD
     * @type {string}
     * @memberof HandlersCreateCampaignRequest
     */
    startDate?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateCampaignRequest
     */
    status?: string;
}

/**
 * Check if a given object implements the HandlersCreateCampaignRequest interface.
 */
export function instanceOfHandlersCreateCampaignRequest(value: object): value is HandlersCreateCampaignRequest {
    if (!('advertiserId' in value) || value['advertiserId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    return true;
}

export function HandlersCreateCampaignRequestFromJSON(json: any): HandlersCreateCampaignRequest {
    return HandlersCreateCampaignRequestFromJSONTyped(json, false);
}

export function HandlersCreateCampaignRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersCreateCampaignRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'advertiserId': json['advertiser_id'],
        'description': json['description'] == null ? undefined : json['description'],
        'endDate': json['end_date'] == null ? undefined : json['end_date'],
        'name': json['name'],
        'organizationId': json['organization_id'],
        'startDate': json['start_date'] == null ? undefined : json['start_date'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function HandlersCreateCampaignRequestToJSON(json: any): HandlersCreateCampaignRequest {
    return HandlersCreateCampaignRequestToJSONTyped(json, false);
}

export function HandlersCreateCampaignRequestToJSONTyped(value?: HandlersCreateCampaignRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advertiser_id': value['advertiserId'],
        'description': value['description'],
        'end_date': value['endDate'],
        'name': value['name'],
        'organization_id': value['organizationId'],
        'start_date': value['startDate'],
        'status': value['status'],
    };
}

