/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersUpdateCampaignRequest
 */
export interface HandlersUpdateCampaignRequest {
    /**
     * 
     * @type {string}
     * @memberof HandlersUpdateCampaignRequest
     */
    description?: string;
    /**
     * Format: YYYY-MM-DD
     * @type {string}
     * @memberof HandlersUpdateCampaignRequest
     */
    endDate?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersUpdateCampaignRequest
     */
    name: string;
    /**
     * Format: YYYY-MM-DD
     * @type {string}
     * @memberof HandlersUpdateCampaignRequest
     */
    startDate?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersUpdateCampaignRequest
     */
    status: string;
}

/**
 * Check if a given object implements the HandlersUpdateCampaignRequest interface.
 */
export function instanceOfHandlersUpdateCampaignRequest(value: object): value is HandlersUpdateCampaignRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function HandlersUpdateCampaignRequestFromJSON(json: any): HandlersUpdateCampaignRequest {
    return HandlersUpdateCampaignRequestFromJSONTyped(json, false);
}

export function HandlersUpdateCampaignRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersUpdateCampaignRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'endDate': json['end_date'] == null ? undefined : json['end_date'],
        'name': json['name'],
        'startDate': json['start_date'] == null ? undefined : json['start_date'],
        'status': json['status'],
    };
}

export function HandlersUpdateCampaignRequestToJSON(json: any): HandlersUpdateCampaignRequest {
    return HandlersUpdateCampaignRequestToJSONTyped(json, false);
}

export function HandlersUpdateCampaignRequestToJSONTyped(value?: HandlersUpdateCampaignRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'end_date': value['endDate'],
        'name': value['name'],
        'start_date': value['startDate'],
        'status': value['status'],
    };
}

