/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HandlersAffiliateExtraInfoRequest } from './HandlersAffiliateExtraInfoRequest';
import {
    HandlersAffiliateExtraInfoRequestFromJSON,
    HandlersAffiliateExtraInfoRequestFromJSONTyped,
    HandlersAffiliateExtraInfoRequestToJSON,
    HandlersAffiliateExtraInfoRequestToJSONTyped,
} from './HandlersAffiliateExtraInfoRequest';
import type { HandlersAdvertiserExtraInfoRequest } from './HandlersAdvertiserExtraInfoRequest';
import {
    HandlersAdvertiserExtraInfoRequestFromJSON,
    HandlersAdvertiserExtraInfoRequestFromJSONTyped,
    HandlersAdvertiserExtraInfoRequestToJSON,
    HandlersAdvertiserExtraInfoRequestToJSONTyped,
} from './HandlersAdvertiserExtraInfoRequest';

/**
 * 
 * @export
 * @interface HandlersCreateOrganizationRequest
 */
export interface HandlersCreateOrganizationRequest {
    /**
     * 
     * @type {HandlersAdvertiserExtraInfoRequest}
     * @memberof HandlersCreateOrganizationRequest
     */
    advertiserExtraInfo?: HandlersAdvertiserExtraInfoRequest;
    /**
     * 
     * @type {HandlersAffiliateExtraInfoRequest}
     * @memberof HandlersCreateOrganizationRequest
     */
    affiliateExtraInfo?: HandlersAffiliateExtraInfoRequest;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateOrganizationRequest
     */
    contactEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateOrganizationRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateOrganizationRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateOrganizationRequest
     */
    type: HandlersCreateOrganizationRequestTypeEnum;
}


/**
 * @export
 */
export const HandlersCreateOrganizationRequestTypeEnum = {
    Advertiser: 'advertiser',
    Affiliate: 'affiliate',
    PlatformOwner: 'platform_owner',
    Agency: 'agency'
} as const;
export type HandlersCreateOrganizationRequestTypeEnum = typeof HandlersCreateOrganizationRequestTypeEnum[keyof typeof HandlersCreateOrganizationRequestTypeEnum];


/**
 * Check if a given object implements the HandlersCreateOrganizationRequest interface.
 */
export function instanceOfHandlersCreateOrganizationRequest(value: object): value is HandlersCreateOrganizationRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function HandlersCreateOrganizationRequestFromJSON(json: any): HandlersCreateOrganizationRequest {
    return HandlersCreateOrganizationRequestFromJSONTyped(json, false);
}

export function HandlersCreateOrganizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersCreateOrganizationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'advertiserExtraInfo': json['advertiser_extra_info'] == null ? undefined : HandlersAdvertiserExtraInfoRequestFromJSON(json['advertiser_extra_info']),
        'affiliateExtraInfo': json['affiliate_extra_info'] == null ? undefined : HandlersAffiliateExtraInfoRequestFromJSON(json['affiliate_extra_info']),
        'contactEmail': json['contact_email'] == null ? undefined : json['contact_email'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
        'type': json['type'],
    };
}

export function HandlersCreateOrganizationRequestToJSON(json: any): HandlersCreateOrganizationRequest {
    return HandlersCreateOrganizationRequestToJSONTyped(json, false);
}

export function HandlersCreateOrganizationRequestToJSONTyped(value?: HandlersCreateOrganizationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advertiser_extra_info': HandlersAdvertiserExtraInfoRequestToJSON(value['advertiserExtraInfo']),
        'affiliate_extra_info': HandlersAffiliateExtraInfoRequestToJSON(value['affiliateExtraInfo']),
        'contact_email': value['contactEmail'],
        'description': value['description'],
        'name': value['name'],
        'type': value['type'],
    };
}

