/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsTrackingLinkResponse
 */
export interface ModelsTrackingLinkResponse {
    /**
     * 
     * @type {number}
     * @memberof ModelsTrackingLinkResponse
     */
    affiliateId?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsTrackingLinkResponse
     */
    campaignId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkResponse
     */
    internalNotes?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsTrackingLinkResponse
     */
    isEncryptParameters?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsTrackingLinkResponse
     */
    isRedirectLink?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkResponse
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsTrackingLinkResponse
     */
    organizationId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkResponse
     */
    sourceId?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkResponse
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkResponse
     */
    sub1?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkResponse
     */
    sub2?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkResponse
     */
    sub3?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkResponse
     */
    sub4?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkResponse
     */
    sub5?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkResponse
     */
    tags?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsTrackingLinkResponse
     */
    trackingLinkId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkResponse
     */
    trackingUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkResponse
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the ModelsTrackingLinkResponse interface.
 */
export function instanceOfModelsTrackingLinkResponse(value: object): value is ModelsTrackingLinkResponse {
    return true;
}

export function ModelsTrackingLinkResponseFromJSON(json: any): ModelsTrackingLinkResponse {
    return ModelsTrackingLinkResponseFromJSONTyped(json, false);
}

export function ModelsTrackingLinkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsTrackingLinkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'affiliateId': json['affiliate_id'] == null ? undefined : json['affiliate_id'],
        'campaignId': json['campaign_id'] == null ? undefined : json['campaign_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'description': json['description'] == null ? undefined : json['description'],
        'internalNotes': json['internal_notes'] == null ? undefined : json['internal_notes'],
        'isEncryptParameters': json['is_encrypt_parameters'] == null ? undefined : json['is_encrypt_parameters'],
        'isRedirectLink': json['is_redirect_link'] == null ? undefined : json['is_redirect_link'],
        'name': json['name'] == null ? undefined : json['name'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'sourceId': json['source_id'] == null ? undefined : json['source_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'sub1': json['sub1'] == null ? undefined : json['sub1'],
        'sub2': json['sub2'] == null ? undefined : json['sub2'],
        'sub3': json['sub3'] == null ? undefined : json['sub3'],
        'sub4': json['sub4'] == null ? undefined : json['sub4'],
        'sub5': json['sub5'] == null ? undefined : json['sub5'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'trackingLinkId': json['tracking_link_id'] == null ? undefined : json['tracking_link_id'],
        'trackingUrl': json['tracking_url'] == null ? undefined : json['tracking_url'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function ModelsTrackingLinkResponseToJSON(json: any): ModelsTrackingLinkResponse {
    return ModelsTrackingLinkResponseToJSONTyped(json, false);
}

export function ModelsTrackingLinkResponseToJSONTyped(value?: ModelsTrackingLinkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'affiliate_id': value['affiliateId'],
        'campaign_id': value['campaignId'],
        'created_at': value['createdAt'],
        'description': value['description'],
        'internal_notes': value['internalNotes'],
        'is_encrypt_parameters': value['isEncryptParameters'],
        'is_redirect_link': value['isRedirectLink'],
        'name': value['name'],
        'organization_id': value['organizationId'],
        'source_id': value['sourceId'],
        'status': value['status'],
        'sub1': value['sub1'],
        'sub2': value['sub2'],
        'sub3': value['sub3'],
        'sub4': value['sub4'],
        'sub5': value['sub5'],
        'tags': value['tags'],
        'tracking_link_id': value['trackingLinkId'],
        'tracking_url': value['trackingUrl'],
        'updated_at': value['updatedAt'],
    };
}

