/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DomainAdvertiserProviderMapping } from './DomainAdvertiserProviderMapping';
import {
    DomainAdvertiserProviderMappingFromJSON,
    DomainAdvertiserProviderMappingFromJSONTyped,
    DomainAdvertiserProviderMappingToJSON,
    DomainAdvertiserProviderMappingToJSONTyped,
} from './DomainAdvertiserProviderMapping';

/**
 * 
 * @export
 * @interface ModelsCreateAdvertiserProviderMappingRequest
 */
export interface ModelsCreateAdvertiserProviderMappingRequest {
    /**
     * 
     * @type {DomainAdvertiserProviderMapping}
     * @memberof ModelsCreateAdvertiserProviderMappingRequest
     */
    providerMapping: DomainAdvertiserProviderMapping;
}

/**
 * Check if a given object implements the ModelsCreateAdvertiserProviderMappingRequest interface.
 */
export function instanceOfModelsCreateAdvertiserProviderMappingRequest(value: object): value is ModelsCreateAdvertiserProviderMappingRequest {
    if (!('providerMapping' in value) || value['providerMapping'] === undefined) return false;
    return true;
}

export function ModelsCreateAdvertiserProviderMappingRequestFromJSON(json: any): ModelsCreateAdvertiserProviderMappingRequest {
    return ModelsCreateAdvertiserProviderMappingRequestFromJSONTyped(json, false);
}

export function ModelsCreateAdvertiserProviderMappingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsCreateAdvertiserProviderMappingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'providerMapping': DomainAdvertiserProviderMappingFromJSON(json['provider_mapping']),
    };
}

export function ModelsCreateAdvertiserProviderMappingRequestToJSON(json: any): ModelsCreateAdvertiserProviderMappingRequest {
    return ModelsCreateAdvertiserProviderMappingRequestToJSONTyped(json, false);
}

export function ModelsCreateAdvertiserProviderMappingRequestToJSONTyped(value?: ModelsCreateAdvertiserProviderMappingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider_mapping': DomainAdvertiserProviderMappingToJSON(value['providerMapping']),
    };
}

