/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsCampaignProviderMappingResponse
 */
export interface ModelsCampaignProviderMappingResponse {
    /**
     * 
     * @type {number}
     * @memberof ModelsCampaignProviderMappingResponse
     */
    campaignId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignProviderMappingResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsCampaignProviderMappingResponse
     */
    isActiveOnProvider?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignProviderMappingResponse
     */
    lastSyncedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCampaignProviderMappingResponse
     */
    mappingId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignProviderMappingResponse
     */
    providerData?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignProviderMappingResponse
     */
    providerOfferId?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignProviderMappingResponse
     */
    providerType?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignProviderMappingResponse
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the ModelsCampaignProviderMappingResponse interface.
 */
export function instanceOfModelsCampaignProviderMappingResponse(value: object): value is ModelsCampaignProviderMappingResponse {
    return true;
}

export function ModelsCampaignProviderMappingResponseFromJSON(json: any): ModelsCampaignProviderMappingResponse {
    return ModelsCampaignProviderMappingResponseFromJSONTyped(json, false);
}

export function ModelsCampaignProviderMappingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsCampaignProviderMappingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'campaignId': json['campaign_id'] == null ? undefined : json['campaign_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'isActiveOnProvider': json['is_active_on_provider'] == null ? undefined : json['is_active_on_provider'],
        'lastSyncedAt': json['last_synced_at'] == null ? undefined : json['last_synced_at'],
        'mappingId': json['mapping_id'] == null ? undefined : json['mapping_id'],
        'providerData': json['provider_data'] == null ? undefined : json['provider_data'],
        'providerOfferId': json['provider_offer_id'] == null ? undefined : json['provider_offer_id'],
        'providerType': json['provider_type'] == null ? undefined : json['provider_type'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function ModelsCampaignProviderMappingResponseToJSON(json: any): ModelsCampaignProviderMappingResponse {
    return ModelsCampaignProviderMappingResponseToJSONTyped(json, false);
}

export function ModelsCampaignProviderMappingResponseToJSONTyped(value?: ModelsCampaignProviderMappingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'campaign_id': value['campaignId'],
        'created_at': value['createdAt'],
        'is_active_on_provider': value['isActiveOnProvider'],
        'last_synced_at': value['lastSyncedAt'],
        'mapping_id': value['mappingId'],
        'provider_data': value['providerData'],
        'provider_offer_id': value['providerOfferId'],
        'provider_type': value['providerType'],
        'updated_at': value['updatedAt'],
    };
}

