/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsCampaignResponse
 */
export interface ModelsCampaignResponse {
    /**
     * 
     * @type {number}
     * @memberof ModelsCampaignResponse
     */
    advertiserId?: number;
    /**
     * Payout and revenue configuration
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    billingModel?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCampaignResponse
     */
    campaignId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    conversionMethod?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    currencyId?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCampaignResponse
     */
    dailyClickCap?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCampaignResponse
     */
    dailyConversionCap?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    description?: string;
    /**
     * Core campaign fields
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    destinationUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    endDate?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCampaignResponse
     */
    globalClickCap?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCampaignResponse
     */
    globalConversionCap?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    internalNotes?: string;
    /**
     * Caps and limits
     * @type {boolean}
     * @memberof ModelsCampaignResponse
     */
    isCapsEnabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ModelsCampaignResponse
     */
    monthlyClickCap?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCampaignResponse
     */
    monthlyConversionCap?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCampaignResponse
     */
    organizationId?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCampaignResponse
     */
    payoutAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    payoutStructure?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    previewUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCampaignResponse
     */
    revenueAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    revenueStructure?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    sessionDefinition?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCampaignResponse
     */
    sessionDuration?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    startDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    termsAndConditions?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    thumbnailUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCampaignResponse
     */
    visibility?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCampaignResponse
     */
    weeklyClickCap?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCampaignResponse
     */
    weeklyConversionCap?: number;
}

/**
 * Check if a given object implements the ModelsCampaignResponse interface.
 */
export function instanceOfModelsCampaignResponse(value: object): value is ModelsCampaignResponse {
    return true;
}

export function ModelsCampaignResponseFromJSON(json: any): ModelsCampaignResponse {
    return ModelsCampaignResponseFromJSONTyped(json, false);
}

export function ModelsCampaignResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsCampaignResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'advertiserId': json['advertiser_id'] == null ? undefined : json['advertiser_id'],
        'billingModel': json['billing_model'] == null ? undefined : json['billing_model'],
        'campaignId': json['campaign_id'] == null ? undefined : json['campaign_id'],
        'conversionMethod': json['conversion_method'] == null ? undefined : json['conversion_method'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'currencyId': json['currency_id'] == null ? undefined : json['currency_id'],
        'dailyClickCap': json['daily_click_cap'] == null ? undefined : json['daily_click_cap'],
        'dailyConversionCap': json['daily_conversion_cap'] == null ? undefined : json['daily_conversion_cap'],
        'description': json['description'] == null ? undefined : json['description'],
        'destinationUrl': json['destination_url'] == null ? undefined : json['destination_url'],
        'endDate': json['end_date'] == null ? undefined : json['end_date'],
        'globalClickCap': json['global_click_cap'] == null ? undefined : json['global_click_cap'],
        'globalConversionCap': json['global_conversion_cap'] == null ? undefined : json['global_conversion_cap'],
        'internalNotes': json['internal_notes'] == null ? undefined : json['internal_notes'],
        'isCapsEnabled': json['is_caps_enabled'] == null ? undefined : json['is_caps_enabled'],
        'monthlyClickCap': json['monthly_click_cap'] == null ? undefined : json['monthly_click_cap'],
        'monthlyConversionCap': json['monthly_conversion_cap'] == null ? undefined : json['monthly_conversion_cap'],
        'name': json['name'] == null ? undefined : json['name'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'payoutAmount': json['payout_amount'] == null ? undefined : json['payout_amount'],
        'payoutStructure': json['payout_structure'] == null ? undefined : json['payout_structure'],
        'previewUrl': json['preview_url'] == null ? undefined : json['preview_url'],
        'revenueAmount': json['revenue_amount'] == null ? undefined : json['revenue_amount'],
        'revenueStructure': json['revenue_structure'] == null ? undefined : json['revenue_structure'],
        'sessionDefinition': json['session_definition'] == null ? undefined : json['session_definition'],
        'sessionDuration': json['session_duration'] == null ? undefined : json['session_duration'],
        'startDate': json['start_date'] == null ? undefined : json['start_date'],
        'status': json['status'] == null ? undefined : json['status'],
        'termsAndConditions': json['terms_and_conditions'] == null ? undefined : json['terms_and_conditions'],
        'thumbnailUrl': json['thumbnail_url'] == null ? undefined : json['thumbnail_url'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'visibility': json['visibility'] == null ? undefined : json['visibility'],
        'weeklyClickCap': json['weekly_click_cap'] == null ? undefined : json['weekly_click_cap'],
        'weeklyConversionCap': json['weekly_conversion_cap'] == null ? undefined : json['weekly_conversion_cap'],
    };
}

export function ModelsCampaignResponseToJSON(json: any): ModelsCampaignResponse {
    return ModelsCampaignResponseToJSONTyped(json, false);
}

export function ModelsCampaignResponseToJSONTyped(value?: ModelsCampaignResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advertiser_id': value['advertiserId'],
        'billing_model': value['billingModel'],
        'campaign_id': value['campaignId'],
        'conversion_method': value['conversionMethod'],
        'created_at': value['createdAt'],
        'currency_id': value['currencyId'],
        'daily_click_cap': value['dailyClickCap'],
        'daily_conversion_cap': value['dailyConversionCap'],
        'description': value['description'],
        'destination_url': value['destinationUrl'],
        'end_date': value['endDate'],
        'global_click_cap': value['globalClickCap'],
        'global_conversion_cap': value['globalConversionCap'],
        'internal_notes': value['internalNotes'],
        'is_caps_enabled': value['isCapsEnabled'],
        'monthly_click_cap': value['monthlyClickCap'],
        'monthly_conversion_cap': value['monthlyConversionCap'],
        'name': value['name'],
        'organization_id': value['organizationId'],
        'payout_amount': value['payoutAmount'],
        'payout_structure': value['payoutStructure'],
        'preview_url': value['previewUrl'],
        'revenue_amount': value['revenueAmount'],
        'revenue_structure': value['revenueStructure'],
        'session_definition': value['sessionDefinition'],
        'session_duration': value['sessionDuration'],
        'start_date': value['startDate'],
        'status': value['status'],
        'terms_and_conditions': value['termsAndConditions'],
        'thumbnail_url': value['thumbnailUrl'],
        'updated_at': value['updatedAt'],
        'visibility': value['visibility'],
        'weekly_click_cap': value['weeklyClickCap'],
        'weekly_conversion_cap': value['weeklyConversionCap'],
    };
}

