/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsCreateCampaignRequest
 */
export interface ModelsCreateCampaignRequest {
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateCampaignRequest
     */
    advertiserId: number;
    /**
     * Payout and revenue configuration
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    billingModel?: ModelsCreateCampaignRequestBillingModelEnum;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    conversionMethod?: ModelsCreateCampaignRequestConversionMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    currencyId?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateCampaignRequest
     */
    dailyClickCap?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateCampaignRequest
     */
    dailyConversionCap?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    description?: string;
    /**
     * Core campaign fields
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    destinationUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    endDate?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateCampaignRequest
     */
    globalClickCap?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateCampaignRequest
     */
    globalConversionCap?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    internalNotes?: string;
    /**
     * Caps and limits
     * @type {boolean}
     * @memberof ModelsCreateCampaignRequest
     */
    isCapsEnabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateCampaignRequest
     */
    monthlyClickCap?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateCampaignRequest
     */
    monthlyConversionCap?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateCampaignRequest
     */
    organizationId: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateCampaignRequest
     */
    payoutAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    payoutStructure?: ModelsCreateCampaignRequestPayoutStructureEnum;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    previewUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateCampaignRequest
     */
    revenueAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    revenueStructure?: ModelsCreateCampaignRequestRevenueStructureEnum;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    sessionDefinition?: ModelsCreateCampaignRequestSessionDefinitionEnum;
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateCampaignRequest
     */
    sessionDuration?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    startDate?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    status: ModelsCreateCampaignRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    termsAndConditions?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    thumbnailUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsCreateCampaignRequest
     */
    visibility?: ModelsCreateCampaignRequestVisibilityEnum;
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateCampaignRequest
     */
    weeklyClickCap?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsCreateCampaignRequest
     */
    weeklyConversionCap?: number;
}


/**
 * @export
 */
export const ModelsCreateCampaignRequestBillingModelEnum = {
    Click: 'click',
    Conversion: 'conversion'
} as const;
export type ModelsCreateCampaignRequestBillingModelEnum = typeof ModelsCreateCampaignRequestBillingModelEnum[keyof typeof ModelsCreateCampaignRequestBillingModelEnum];

/**
 * @export
 */
export const ModelsCreateCampaignRequestConversionMethodEnum = {
    ServerPostback: 'server_postback',
    Pixel: 'pixel'
} as const;
export type ModelsCreateCampaignRequestConversionMethodEnum = typeof ModelsCreateCampaignRequestConversionMethodEnum[keyof typeof ModelsCreateCampaignRequestConversionMethodEnum];

/**
 * @export
 */
export const ModelsCreateCampaignRequestPayoutStructureEnum = {
    Fixed: 'fixed',
    Percentage: 'percentage'
} as const;
export type ModelsCreateCampaignRequestPayoutStructureEnum = typeof ModelsCreateCampaignRequestPayoutStructureEnum[keyof typeof ModelsCreateCampaignRequestPayoutStructureEnum];

/**
 * @export
 */
export const ModelsCreateCampaignRequestRevenueStructureEnum = {
    Fixed: 'fixed',
    Percentage: 'percentage'
} as const;
export type ModelsCreateCampaignRequestRevenueStructureEnum = typeof ModelsCreateCampaignRequestRevenueStructureEnum[keyof typeof ModelsCreateCampaignRequestRevenueStructureEnum];

/**
 * @export
 */
export const ModelsCreateCampaignRequestSessionDefinitionEnum = {
    Cookie: 'cookie',
    Ip: 'ip',
    Fingerprint: 'fingerprint'
} as const;
export type ModelsCreateCampaignRequestSessionDefinitionEnum = typeof ModelsCreateCampaignRequestSessionDefinitionEnum[keyof typeof ModelsCreateCampaignRequestSessionDefinitionEnum];

/**
 * @export
 */
export const ModelsCreateCampaignRequestStatusEnum = {
    Draft: 'draft',
    Active: 'active',
    Paused: 'paused',
    Archived: 'archived'
} as const;
export type ModelsCreateCampaignRequestStatusEnum = typeof ModelsCreateCampaignRequestStatusEnum[keyof typeof ModelsCreateCampaignRequestStatusEnum];

/**
 * @export
 */
export const ModelsCreateCampaignRequestVisibilityEnum = {
    Public: 'public',
    RequireApproval: 'require_approval',
    Private: 'private'
} as const;
export type ModelsCreateCampaignRequestVisibilityEnum = typeof ModelsCreateCampaignRequestVisibilityEnum[keyof typeof ModelsCreateCampaignRequestVisibilityEnum];


/**
 * Check if a given object implements the ModelsCreateCampaignRequest interface.
 */
export function instanceOfModelsCreateCampaignRequest(value: object): value is ModelsCreateCampaignRequest {
    if (!('advertiserId' in value) || value['advertiserId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ModelsCreateCampaignRequestFromJSON(json: any): ModelsCreateCampaignRequest {
    return ModelsCreateCampaignRequestFromJSONTyped(json, false);
}

export function ModelsCreateCampaignRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsCreateCampaignRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'advertiserId': json['advertiser_id'],
        'billingModel': json['billing_model'] == null ? undefined : json['billing_model'],
        'conversionMethod': json['conversion_method'] == null ? undefined : json['conversion_method'],
        'currencyId': json['currency_id'] == null ? undefined : json['currency_id'],
        'dailyClickCap': json['daily_click_cap'] == null ? undefined : json['daily_click_cap'],
        'dailyConversionCap': json['daily_conversion_cap'] == null ? undefined : json['daily_conversion_cap'],
        'description': json['description'] == null ? undefined : json['description'],
        'destinationUrl': json['destination_url'] == null ? undefined : json['destination_url'],
        'endDate': json['end_date'] == null ? undefined : json['end_date'],
        'globalClickCap': json['global_click_cap'] == null ? undefined : json['global_click_cap'],
        'globalConversionCap': json['global_conversion_cap'] == null ? undefined : json['global_conversion_cap'],
        'internalNotes': json['internal_notes'] == null ? undefined : json['internal_notes'],
        'isCapsEnabled': json['is_caps_enabled'] == null ? undefined : json['is_caps_enabled'],
        'monthlyClickCap': json['monthly_click_cap'] == null ? undefined : json['monthly_click_cap'],
        'monthlyConversionCap': json['monthly_conversion_cap'] == null ? undefined : json['monthly_conversion_cap'],
        'name': json['name'],
        'organizationId': json['organization_id'],
        'payoutAmount': json['payout_amount'] == null ? undefined : json['payout_amount'],
        'payoutStructure': json['payout_structure'] == null ? undefined : json['payout_structure'],
        'previewUrl': json['preview_url'] == null ? undefined : json['preview_url'],
        'revenueAmount': json['revenue_amount'] == null ? undefined : json['revenue_amount'],
        'revenueStructure': json['revenue_structure'] == null ? undefined : json['revenue_structure'],
        'sessionDefinition': json['session_definition'] == null ? undefined : json['session_definition'],
        'sessionDuration': json['session_duration'] == null ? undefined : json['session_duration'],
        'startDate': json['start_date'] == null ? undefined : json['start_date'],
        'status': json['status'],
        'termsAndConditions': json['terms_and_conditions'] == null ? undefined : json['terms_and_conditions'],
        'thumbnailUrl': json['thumbnail_url'] == null ? undefined : json['thumbnail_url'],
        'visibility': json['visibility'] == null ? undefined : json['visibility'],
        'weeklyClickCap': json['weekly_click_cap'] == null ? undefined : json['weekly_click_cap'],
        'weeklyConversionCap': json['weekly_conversion_cap'] == null ? undefined : json['weekly_conversion_cap'],
    };
}

export function ModelsCreateCampaignRequestToJSON(json: any): ModelsCreateCampaignRequest {
    return ModelsCreateCampaignRequestToJSONTyped(json, false);
}

export function ModelsCreateCampaignRequestToJSONTyped(value?: ModelsCreateCampaignRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advertiser_id': value['advertiserId'],
        'billing_model': value['billingModel'],
        'conversion_method': value['conversionMethod'],
        'currency_id': value['currencyId'],
        'daily_click_cap': value['dailyClickCap'],
        'daily_conversion_cap': value['dailyConversionCap'],
        'description': value['description'],
        'destination_url': value['destinationUrl'],
        'end_date': value['endDate'],
        'global_click_cap': value['globalClickCap'],
        'global_conversion_cap': value['globalConversionCap'],
        'internal_notes': value['internalNotes'],
        'is_caps_enabled': value['isCapsEnabled'],
        'monthly_click_cap': value['monthlyClickCap'],
        'monthly_conversion_cap': value['monthlyConversionCap'],
        'name': value['name'],
        'organization_id': value['organizationId'],
        'payout_amount': value['payoutAmount'],
        'payout_structure': value['payoutStructure'],
        'preview_url': value['previewUrl'],
        'revenue_amount': value['revenueAmount'],
        'revenue_structure': value['revenueStructure'],
        'session_definition': value['sessionDefinition'],
        'session_duration': value['sessionDuration'],
        'start_date': value['startDate'],
        'status': value['status'],
        'terms_and_conditions': value['termsAndConditions'],
        'thumbnail_url': value['thumbnailUrl'],
        'visibility': value['visibility'],
        'weekly_click_cap': value['weeklyClickCap'],
        'weekly_conversion_cap': value['weeklyConversionCap'],
    };
}

