/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsTrackingLinkRequest
 */
export interface ModelsTrackingLinkRequest {
    /**
     * 
     * @type {number}
     * @memberof ModelsTrackingLinkRequest
     */
    affiliateId: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsTrackingLinkRequest
     */
    campaignId: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkRequest
     */
    internalNotes?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsTrackingLinkRequest
     */
    isEncryptParameters?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsTrackingLinkRequest
     */
    isRedirectLink?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkRequest
     */
    sourceId?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkRequest
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkRequest
     */
    sub1?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkRequest
     */
    sub2?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkRequest
     */
    sub3?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkRequest
     */
    sub4?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkRequest
     */
    sub5?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkRequest
     */
    tags?: string;
}

/**
 * Check if a given object implements the ModelsTrackingLinkRequest interface.
 */
export function instanceOfModelsTrackingLinkRequest(value: object): value is ModelsTrackingLinkRequest {
    if (!('affiliateId' in value) || value['affiliateId'] === undefined) return false;
    if (!('campaignId' in value) || value['campaignId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ModelsTrackingLinkRequestFromJSON(json: any): ModelsTrackingLinkRequest {
    return ModelsTrackingLinkRequestFromJSONTyped(json, false);
}

export function ModelsTrackingLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsTrackingLinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'affiliateId': json['affiliate_id'],
        'campaignId': json['campaign_id'],
        'description': json['description'] == null ? undefined : json['description'],
        'internalNotes': json['internal_notes'] == null ? undefined : json['internal_notes'],
        'isEncryptParameters': json['is_encrypt_parameters'] == null ? undefined : json['is_encrypt_parameters'],
        'isRedirectLink': json['is_redirect_link'] == null ? undefined : json['is_redirect_link'],
        'name': json['name'],
        'sourceId': json['source_id'] == null ? undefined : json['source_id'],
        'status': json['status'],
        'sub1': json['sub1'] == null ? undefined : json['sub1'],
        'sub2': json['sub2'] == null ? undefined : json['sub2'],
        'sub3': json['sub3'] == null ? undefined : json['sub3'],
        'sub4': json['sub4'] == null ? undefined : json['sub4'],
        'sub5': json['sub5'] == null ? undefined : json['sub5'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function ModelsTrackingLinkRequestToJSON(json: any): ModelsTrackingLinkRequest {
    return ModelsTrackingLinkRequestToJSONTyped(json, false);
}

export function ModelsTrackingLinkRequestToJSONTyped(value?: ModelsTrackingLinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'affiliate_id': value['affiliateId'],
        'campaign_id': value['campaignId'],
        'description': value['description'],
        'internal_notes': value['internalNotes'],
        'is_encrypt_parameters': value['isEncryptParameters'],
        'is_redirect_link': value['isRedirectLink'],
        'name': value['name'],
        'source_id': value['sourceId'],
        'status': value['status'],
        'sub1': value['sub1'],
        'sub2': value['sub2'],
        'sub3': value['sub3'],
        'sub4': value['sub4'],
        'sub5': value['sub5'],
        'tags': value['tags'],
    };
}

