/* tslint:disable */
/* eslint-disable */
/**
 * Affiliate Backend API
 * API Server for Affiliate Backend Application
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsTrackingLinkResponse } from './ModelsTrackingLinkResponse';
import {
    ModelsTrackingLinkResponseFromJSON,
    ModelsTrackingLinkResponseFromJSONTyped,
    ModelsTrackingLinkResponseToJSON,
    ModelsTrackingLinkResponseToJSONTyped,
} from './ModelsTrackingLinkResponse';

/**
 * 
 * @export
 * @interface ModelsTrackingLinkGenerationResponse
 */
export interface ModelsTrackingLinkGenerationResponse {
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkGenerationResponse
     */
    generatedUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsTrackingLinkGenerationResponse
     */
    qrCodeUrl?: string;
    /**
     * 
     * @type {ModelsTrackingLinkResponse}
     * @memberof ModelsTrackingLinkGenerationResponse
     */
    trackingLink?: ModelsTrackingLinkResponse;
}

/**
 * Check if a given object implements the ModelsTrackingLinkGenerationResponse interface.
 */
export function instanceOfModelsTrackingLinkGenerationResponse(value: object): value is ModelsTrackingLinkGenerationResponse {
    return true;
}

export function ModelsTrackingLinkGenerationResponseFromJSON(json: any): ModelsTrackingLinkGenerationResponse {
    return ModelsTrackingLinkGenerationResponseFromJSONTyped(json, false);
}

export function ModelsTrackingLinkGenerationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsTrackingLinkGenerationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'generatedUrl': json['generated_url'] == null ? undefined : json['generated_url'],
        'qrCodeUrl': json['qr_code_url'] == null ? undefined : json['qr_code_url'],
        'trackingLink': json['tracking_link'] == null ? undefined : ModelsTrackingLinkResponseFromJSON(json['tracking_link']),
    };
}

export function ModelsTrackingLinkGenerationResponseToJSON(json: any): ModelsTrackingLinkGenerationResponse {
    return ModelsTrackingLinkGenerationResponseToJSONTyped(json, false);
}

export function ModelsTrackingLinkGenerationResponseToJSONTyped(value?: ModelsTrackingLinkGenerationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generated_url': value['generatedUrl'],
        'qr_code_url': value['qrCodeUrl'],
        'tracking_link': ModelsTrackingLinkResponseToJSON(value['trackingLink']),
    };
}

